# -*- coding: utf-8 -*-
# Testi delle landing page per paese — lingue dell'Europa occidentale.
# Segnaposto: {n} {nom} {N} {in} {to} (forme del nome del paese, vedi seo_countries.py)
#             {city} {km} {days} {hubs} {sectors}
L = {}

# --------------------------------------------------------------- ENGLISH
L['en'] = dict(
 code='en', kw='CNC machining', svc_name='CNC machining and custom machine building for {n}',
 title='CNC Machining Supplier for {n} | DajbocTechDon, Romania',
 desc='Precision CNC turning & milling, custom machines and metal parts made in Romania and delivered {to} in {days} working days. Prototypes & series – request a quote.',
 h1='CNC machining &amp; custom machine building <span class="gt">for customers {in}</span>',
 badge='Made in Romania · delivered {to}',
 lead='DajbocTechDon S.R.L. machines precision metal components and designs and builds custom machines in its own workshop in Satu Mare, Romania. We supply companies {in} with prototypes, one-off parts, spare parts and small to medium series – from your drawing to delivery at your door.',
 cta_quote='Request a quote', cta_services='Our services',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km straight line',
 f_transit='Transit time (indicative)', f_transit_v='{days} working days',
 f_customs='Customs', f_quote='Quotes', f_quote_v='EUR · English',
 customs_short=dict(eu='None – EU single market', eea='EEA · export docs by us', fta='EU FTA · export docs by us'),
 customs_long=dict(
  eu='Like Romania, {nom} is a member of the European Union, so there are no customs formalities and no duties. B2B deliveries to companies with a valid EU VAT number are invoiced as intra-community supplies without Romanian VAT (reverse charge).',
  eea='{nom} is part of the European Economic Area but not of the EU customs union. We prepare the export declaration and the statement of EU preferential origin, which usually allows industrial goods to be imported duty-free; import VAT is settled {in} on arrival.',
  fta='{nom} is outside the EU customs union but has a free trade agreement with the EU. We prepare the export declaration and the statement on origin, so industrial goods of EU preferential origin usually enter duty-free; import VAT is settled {in} on arrival.'),
 svc_tag='What we do', svc_title='Engineering and CNC services for {n}',
 svc_intro='One supplier for the whole chain – from the first requirements to the finished, tested product delivered {to}.',
 svc=[('Requirements & engineering', 'We clarify goals, specifications, tolerances, materials and quantities with you before any design work starts.'),
      ('Mechanical design', 'Design of parts, devices and custom machines for automotive, industrial, agricultural and energy applications.'),
      ('Simulation', 'Verification of load capacity, compliance and conformity of the design before production.'),
      ('CNC turning & milling', 'Precision CNC machining of metal components in-house – from single prototypes to series.'),
      ('Assembly', 'Assembly of machined and purchased parts into complete, working units.'),
      ('Production control', 'Process management and quality control at every stage of production.'),
      ('Testing', 'Functional and dimensional checks so every part meets safety and performance requirements.'),
      ('Logistics & delivery', 'Packing, documents and transport to your site, anywhere in Europe.')],
 ind_tag='Industries', ind_title='Industries we serve {in}',
 ind_intro='Industry {in} is particularly strong in {sectors}. For companies in these fields we produce components, spare parts and special machines:',
 ind=[('Automotive', 'Precision turned and milled parts, fixtures and assemblies for vehicle manufacturers and their suppliers.'),
      ('Industrial & machinery', 'Custom devices, special machines, jigs and spare parts for production lines and maintenance.'),
      ('Agricultural', 'Components and equipment for agricultural machinery, built for tough field conditions.'),
      ('Energy', 'Parts and assemblies for power generation and energy infrastructure, made for safety and reliability.')],
 why_tag='Why Romania', why_title='Why work with a CNC partner in Romania',
 why=['Romania is in the EU – EU standards, EU contract law and simple cross-border trade.',
      'Competitive production costs combined with modern CNC equipment.',
      'Everything in one workshop: design, simulation, machining, assembly and testing.',
      'Prototypes, one-off parts and small or medium series – no large minimum order quantities.',
      'Direct contact with the engineers who make your parts.'],
 img_alt='CNC machining at the DajbocTechDon workshop in Satu Mare, Romania',
 how_tag='How it works', how_title='From drawing to delivery in four steps',
 how=[('Send your request', 'Drawing or 3D model (PDF, STEP, IGES, DXF), material, quantity and required date.'),
      ('Receive a quote', 'We check feasibility and send you a price and a lead time.'),
      ('Production', 'Machining, assembly and testing in our workshop, with quality control at every step.'),
      ('Delivery', 'Packed, documented and shipped to your address.')],
 log_tag='Logistics', log_title='Delivery {to}: transit times, customs and VAT',
 log_p1='Our workshop is in Turț, Satu Mare County, in north-west Romania – about {km} km in a straight line from {city}. Parts and assemblies travel by road freight (groupage or dedicated truck), or by express courier for small urgent parts; typical road transit {to} is {days} working days. We deliver anywhere {in}, including industrial areas such as {hubs}.',
 log_p3='Delivery terms (for example EXW, FCA or DAP to your plant) are agreed in the quote. Parts are cleaned, protected against corrosion where needed and packed for transport, and each shipment travels with its delivery documents and, on request, inspection reports.',
 faq_title='Questions from customers {in}',
 faq=[('Do you deliver CNC machined parts {to}?', 'Yes. We ship machined parts, assemblies and complete machines {to} by road freight or courier. Typical road transit from Satu Mare {to} is {days} working days, depending on the exact location and transport mode.'),
      ('What do you need to prepare a quote?', 'A technical drawing or 3D model (PDF, STEP, IGES or DXF), the material, the quantity and your required delivery date. If you only have a sample or an idea, we can start from the requirements and design the part for you.'),
      ('Do you make prototypes and one-off parts?', 'Yes. We manufacture prototypes, single parts and spare parts as well as small and medium series; every part is machined and checked in our own workshop.'),
      ('Which language do you work in?', 'Our team works in English and Romanian. Quotes, drawings and delivery documents can be provided in English.')],
 faq_customs_q='Are there customs duties or VAT on deliveries {to}?',
 con_tag='Contact', con_title='Request a quote',
 con_p='Send us your drawing and requirements and we will get back to you with a price and lead time for delivery {to}.',
 l_phone='Phone', l_addr='Address', romania='Romania',
 f_name='Name', f_email='Email', f_company='Company (optional)', f_msg='Message – describe your part or project',
 f_send='Send request', f_sending='Sending…', f_sent='✓ Sent – we will get back to you shortly.', f_error='✗ Error – please try again', f_missing='Please fill in your name, email and message.',
 more_tag='Europe', more_title='We deliver across Europe', more_all='All countries',
 bc_home='Home', bc_eu='Europe', bc_page='{N}',
 nav_home='Home', nav_services='Services', nav_contact='Contact', skip='Skip to content',
 foot='CNC machining and custom machine building, Satu Mare, Romania',
)

# --------------------------------------------------------------- DEUTSCH
L['de'] = dict(
 code='de', kw='CNC-Bearbeitung', svc_name='CNC-Lohnfertigung und Sondermaschinenbau für {n}',
 title='CNC-Lohnfertigung für {n} | Made in Romania – DajbocTechDon',
 desc='CNC-Drehen und -Fräsen, Sondermaschinenbau und Metallteile aus Rumänien – Lieferung {to} in {days} Werktagen. Prototypen und Serien. Jetzt Angebot anfordern.',
 h1='CNC-Bearbeitung &amp; Sondermaschinenbau <span class="gt">für Kunden {in}</span>',
 badge='Made in Romania · Lieferung {to}',
 lead='DajbocTechDon S.R.L. fertigt Präzisions-Metallteile auf CNC-Maschinen und konstruiert und baut Sondermaschinen – alles in der eigenen Werkstatt in Satu Mare, Rumänien. Wir beliefern Unternehmen {in} mit Prototypen, Einzelteilen, Ersatzteilen sowie Klein- und Mittelserien – von Ihrer Zeichnung bis zur Lieferung frei Haus.',
 cta_quote='Angebot anfordern', cta_services='Unsere Leistungen',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km Luftlinie',
 f_transit='Transit per Lkw (Richtwert)', f_transit_v='{days} Werktage',
 f_customs='Zoll', f_quote='Angebote', f_quote_v='in EUR · Englisch',
 customs_short=dict(eu='Kein Zoll – EU-Binnenmarkt', eea='EWR · Ausfuhrpapiere von uns', fta='Freihandel EU · Ausfuhrpapiere von uns'),
 customs_long=dict(
  eu='{nom} ist wie Rumänien Mitglied der Europäischen Union: keine Zollformalitäten, keine Zölle. Lieferungen an Unternehmen mit gültiger USt-IdNr. stellen wir als innergemeinschaftliche Lieferung ohne rumänische Mehrwertsteuer in Rechnung (Reverse-Charge-Verfahren).',
  eea='{nom} gehört zum Europäischen Wirtschaftsraum (EWR), aber nicht zur EU-Zollunion. Wir erstellen die Ausfuhranmeldung und die Erklärung zum präferenziellen EU-Ursprung, sodass Industriewaren in der Regel zollfrei eingeführt werden können; die Einfuhrumsatzsteuer wird {in} bei der Einfuhr abgerechnet.',
  fta='{nom} gehört nicht zur EU-Zollunion, hat aber ein Freihandelsabkommen mit der EU. Wir erstellen die Ausfuhranmeldung und die Ursprungserklärung, sodass Industriewaren mit präferenziellem EU-Ursprung in der Regel zollfrei eingeführt werden; die Einfuhrumsatzsteuer wird {in} bei der Einfuhr abgerechnet.'),
 svc_tag='Leistungen', svc_title='CNC-Fertigung und Engineering für {n}',
 svc_intro='Ein Lieferant für die gesamte Kette – von den ersten Anforderungen bis zum fertigen, geprüften Produkt, geliefert {to}.',
 svc=[('Anforderungen & Engineering', 'Wir klären Ziele, Spezifikationen, Toleranzen, Werkstoffe und Stückzahlen mit Ihnen, bevor die Konstruktion beginnt.'),
      ('Konstruktion', 'Konstruktion von Bauteilen, Vorrichtungen und Sondermaschinen für Automobil, Industrie, Landtechnik und Energie.'),
      ('Simulation', 'Prüfung von Tragfähigkeit, Normkonformität und Funktion der Konstruktion vor der Fertigung.'),
      ('CNC-Drehen & -Fräsen', 'Präzise CNC-Bearbeitung von Metallteilen im eigenen Haus – vom Prototyp bis zur Serie.'),
      ('Montage', 'Montage von gefertigten und zugekauften Teilen zu kompletten, funktionsfähigen Baugruppen.'),
      ('Fertigungssteuerung', 'Prozesssteuerung und Qualitätskontrolle in jeder Phase der Produktion.'),
      ('Prüfung', 'Maß- und Funktionsprüfung, damit jedes Teil die Sicherheits- und Leistungsanforderungen erfüllt.'),
      ('Logistik & Lieferung', 'Verpackung, Papiere und Transport bis zu Ihrem Werk – überall in Europa.')],
 ind_tag='Branchen', ind_title='Branchen, die wir {in} beliefern',
 ind_intro='Die Industrie {in} ist besonders stark in folgenden Bereichen: {sectors}. Für Unternehmen dieser Branchen fertigen wir Bauteile, Ersatzteile und Sondermaschinen:',
 ind=[('Automobil', 'Präzisions-Dreh- und Frästeile, Vorrichtungen und Baugruppen für Fahrzeughersteller und Zulieferer.'),
      ('Industrie & Maschinenbau', 'Sondermaschinen, Vorrichtungen, Lehren und Ersatzteile für Produktionslinien und Instandhaltung.'),
      ('Landtechnik', 'Komponenten und Ausrüstung für Landmaschinen, gebaut für harte Einsatzbedingungen.'),
      ('Energie', 'Teile und Baugruppen für Energieerzeugung und Energieinfrastruktur – sicher und zuverlässig.')],
 why_tag='Warum Rumänien', why_title='Warum ein CNC-Partner in Rumänien?',
 why=['Rumänien ist EU-Mitglied – EU-Normen, EU-Vertragsrecht und unkomplizierter Warenverkehr.',
      'Wettbewerbsfähige Fertigungskosten und moderne CNC-Maschinen.',
      'Alles aus einer Werkstatt: Konstruktion, Simulation, Zerspanung, Montage und Prüfung.',
      'Prototypen, Einzelteile, Klein- und Mittelserien – keine hohen Mindestmengen.',
      'Direkter Kontakt zu den Ingenieuren, die Ihre Teile fertigen.'],
 img_alt='CNC-Bearbeitung in der Werkstatt von DajbocTechDon in Satu Mare, Rumänien',
 how_tag='Ablauf', how_title='Von der Zeichnung zur Lieferung in vier Schritten',
 how=[('Anfrage senden', 'Zeichnung oder 3D-Modell (PDF, STEP, IGES, DXF), Werkstoff, Stückzahl und Wunschtermin.'),
      ('Angebot erhalten', 'Wir prüfen die Machbarkeit und nennen Ihnen Preis und Lieferzeit.'),
      ('Fertigung', 'Zerspanung, Montage und Prüfung in unserer Werkstatt – mit Qualitätskontrolle in jedem Schritt.'),
      ('Lieferung', 'Verpackt, dokumentiert und an Ihre Adresse versandt.')],
 log_tag='Logistik', log_title='Lieferung {to}: Transitzeiten, Zoll und Mehrwertsteuer',
 log_p1='Unsere Werkstatt liegt in Turț im Kreis Satu Mare im Nordwesten Rumäniens – rund {km} km Luftlinie von {city} entfernt. Teile und Baugruppen versenden wir per Lkw (Sammelgut oder Direktfahrt) oder, bei kleinen Eilteilen, per Expresskurier; die übliche Transitzeit {to} beträgt {days} Werktage. Wir liefern überallhin {in}, auch in Industrieregionen wie {hubs}.',
 log_p3='Die Lieferbedingungen (z. B. EXW, FCA oder DAP Ihr Werk) werden im Angebot vereinbart. Die Teile werden gereinigt, bei Bedarf konserviert und transportsicher verpackt; jede Sendung enthält die Lieferpapiere und auf Wunsch Prüfprotokolle.',
 faq_title='Fragen von Kunden {in}',
 faq=[('Liefern Sie CNC-Teile {to}?', 'Ja. Wir versenden Drehteile, Frästeile, Baugruppen und komplette Maschinen {to} per Lkw oder Kurier. Die übliche Transitzeit ab Satu Mare {to} beträgt {days} Werktage, je nach Zielort und Versandart.'),
      ('Was benötigen Sie für ein Angebot?', 'Eine technische Zeichnung oder ein 3D-Modell (PDF, STEP, IGES oder DXF), den Werkstoff, die Stückzahl und Ihren Wunschtermin. Wenn Sie nur ein Muster oder eine Idee haben, beginnen wir mit den Anforderungen und konstruieren das Teil für Sie.'),
      ('Fertigen Sie auch Prototypen und Einzelteile?', 'Ja. Wir fertigen Prototypen, Einzel- und Ersatzteile sowie Klein- und Mittelserien; jedes Teil wird in unserer eigenen Werkstatt bearbeitet und geprüft.'),
      ('In welcher Sprache können wir kommunizieren?', 'Unser Team arbeitet auf Englisch und Rumänisch. Angebote, Zeichnungen und Lieferpapiere erhalten Sie auf Englisch; Ihre Anfrage können Sie uns gerne auch auf Deutsch senden.')],
 faq_customs_q='Fallen bei Lieferungen {to} Zoll oder Mehrwertsteuer an?',
 con_tag='Kontakt', con_title='Angebot anfordern',
 con_p='Senden Sie uns Ihre Zeichnung und Anforderungen – Sie erhalten Preis und Lieferzeit für die Lieferung {to}.',
 l_phone='Telefon', l_addr='Adresse', romania='Rumänien',
 f_name='Name', f_email='E-Mail', f_company='Firma (optional)', f_msg='Nachricht – beschreiben Sie Ihr Teil oder Projekt',
 f_send='Anfrage senden', f_sending='Wird gesendet…', f_sent='✓ Gesendet – wir melden uns in Kürze.', f_error='✗ Fehler – bitte erneut versuchen', f_missing='Bitte Name, E-Mail und Nachricht ausfüllen.',
 more_tag='Europa', more_title='Wir liefern in ganz Europa', more_all='Alle Länder',
 bc_home='Startseite', bc_eu='Europa', bc_page='{N}',
 nav_home='Start', nav_services='Leistungen', nav_contact='Kontakt', skip='Zum Inhalt springen',
 foot='CNC-Bearbeitung und Sondermaschinenbau, Satu Mare, Rumänien',
)

# --------------------------------------------------------------- FRANÇAIS
L['fr'] = dict(
 code='fr', kw='Usinage CNC', svc_name='Usinage CNC et machines spéciales pour {n}',
 title='Usinage CNC pour {n} | Sous-traitance en Roumanie – DajbocTechDon',
 desc='Tournage et fraisage CNC, machines spéciales et pièces métalliques fabriqués en Roumanie, livrés {to} en {days} jours ouvrés. Prototypes et séries – demandez un devis.',
 h1='Usinage CNC &amp; machines spéciales <span class="gt">pour les entreprises {in}</span>',
 badge='Fabriqué en Roumanie · livré {to}',
 lead='DajbocTechDon S.R.L. usine des pièces métalliques de précision et conçoit et fabrique des machines spéciales dans son propre atelier de Satu Mare, en Roumanie. Nous fournissons aux entreprises {in} des prototypes, des pièces unitaires, des pièces de rechange et des petites et moyennes séries – de votre plan jusqu’à la livraison.',
 cta_quote='Demander un devis', cta_services='Nos services',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km à vol d’oiseau',
 f_transit='Transport routier (indicatif)', f_transit_v='{days} jours ouvrés',
 f_customs='Douane', f_quote='Devis', f_quote_v='en EUR · anglais',
 customs_short=dict(eu='Aucune – marché unique UE', mc='Aucune – territoire douanier UE', fta='Accord UE · documents export fournis'),
 customs_long=dict(
  eu='Comme la Roumanie, {nom} est membre de l’Union européenne : aucune formalité douanière, aucun droit de douane. Les livraisons aux entreprises disposant d’un numéro de TVA intracommunautaire valide sont facturées en livraison intracommunautaire, sans TVA roumaine (autoliquidation).',
  mc='Monaco fait partie du territoire douanier de l’Union européenne et, pour la TVA, est traité comme la France : aucune formalité douanière, aucun droit. Les livraisons aux entreprises disposant d’un numéro de TVA valide sont facturées sans TVA roumaine (autoliquidation).',
  fta='{nom} ne fait pas partie de l’union douanière de l’UE mais a conclu un accord de libre-échange avec elle. Nous établissons la déclaration d’exportation et la déclaration d’origine ; les produits industriels d’origine préférentielle UE entrent en général en franchise de droits. La TVA à l’importation est réglée {in} à l’arrivée.'),
 svc_tag='Nos métiers', svc_title='Usinage CNC et ingénierie pour {n}',
 svc_intro='Un seul fournisseur pour toute la chaîne – du cahier des charges au produit fini et testé, livré {to}.',
 svc=[('Cahier des charges', 'Nous définissons avec vous objectifs, spécifications, tolérances, matériaux et quantités avant toute conception.'),
      ('Conception mécanique', 'Conception de pièces, d’outillages et de machines spéciales pour l’automobile, l’industrie, l’agriculture et l’énergie.'),
      ('Simulation', 'Vérification de la résistance, de la conformité et du fonctionnement de la conception avant la fabrication.'),
      ('Tournage & fraisage CNC', 'Usinage CNC de précision de pièces métalliques dans notre atelier – du prototype à la série.'),
      ('Assemblage', 'Assemblage des pièces usinées et achetées en sous-ensembles complets et fonctionnels.'),
      ('Pilotage de production', 'Gestion du processus et contrôle qualité à chaque étape de la fabrication.'),
      ('Essais', 'Contrôles dimensionnels et fonctionnels pour garantir sécurité et performance de chaque pièce.'),
      ('Logistique & livraison', 'Emballage, documents et transport jusqu’à votre site, partout en Europe.')],
 ind_tag='Secteurs', ind_title='Secteurs que nous servons {in}',
 ind_intro='L’industrie {in} est particulièrement forte dans les domaines suivants : {sectors}. Pour les entreprises de ces secteurs, nous fabriquons composants, pièces de rechange et machines spéciales :',
 ind=[('Automobile', 'Pièces tournées et fraisées de précision, montages et sous-ensembles pour constructeurs et équipementiers.'),
      ('Industrie & machines', 'Machines spéciales, montages, gabarits et pièces de rechange pour lignes de production et maintenance.'),
      ('Agricole', 'Composants et équipements pour machines agricoles, conçus pour des conditions d’utilisation difficiles.'),
      ('Énergie', 'Pièces et sous-ensembles pour la production et les infrastructures d’énergie, sûrs et fiables.')],
 why_tag='Pourquoi la Roumanie', why_title='Pourquoi un sous-traitant CNC en Roumanie ?',
 why=['La Roumanie est membre de l’UE : normes européennes, droit européen des contrats et échanges simplifiés.',
      'Des coûts de production compétitifs et un parc de machines CNC moderne.',
      'Tout dans un même atelier : conception, simulation, usinage, assemblage et essais.',
      'Prototypes, pièces unitaires, petites et moyennes séries – sans grosses quantités minimales.',
      'Un contact direct avec les ingénieurs qui fabriquent vos pièces.'],
 img_alt='Usinage CNC dans l’atelier DajbocTechDon à Satu Mare, Roumanie',
 how_tag='Méthode', how_title='Du plan à la livraison en quatre étapes',
 how=[('Envoyez votre demande', 'Plan ou modèle 3D (PDF, STEP, IGES, DXF), matière, quantité et date souhaitée.'),
      ('Recevez un devis', 'Nous vérifions la faisabilité et vous indiquons prix et délai.'),
      ('Fabrication', 'Usinage, assemblage et essais dans notre atelier, avec contrôle qualité à chaque étape.'),
      ('Livraison', 'Emballé, documenté et expédié à votre adresse.')],
 log_tag='Logistique', log_title='Livraison {to} : délais, douane et TVA',
 log_p1='Notre atelier est situé à Turț, dans le département de Satu Mare, au nord-ouest de la Roumanie – à environ {km} km à vol d’oiseau de {city}. Les pièces voyagent par la route (groupage ou camion complet) ou par coursier express pour les petites pièces urgentes ; le délai de transport habituel {to} est de {days} jours ouvrés. Nous livrons partout {in}, y compris dans les bassins industriels comme {hubs}.',
 log_p3='Les conditions de livraison (par exemple EXW, FCA ou DAP votre usine) sont fixées dans le devis. Les pièces sont nettoyées, protégées contre la corrosion si nécessaire et emballées pour le transport ; chaque envoi est accompagné des documents de livraison et, sur demande, des rapports de contrôle.',
 faq_title='Questions des clients {in}',
 faq=[('Livrez-vous des pièces usinées {to} ?', 'Oui. Nous expédions pièces usinées, sous-ensembles et machines complètes {to} par la route ou par coursier. Le délai de transport habituel depuis Satu Mare est de {days} jours ouvrés, selon la destination et le mode de transport.'),
      ('De quoi avez-vous besoin pour un devis ?', 'D’un plan ou d’un modèle 3D (PDF, STEP, IGES ou DXF), de la matière, de la quantité et de la date de livraison souhaitée. Si vous n’avez qu’un échantillon ou une idée, nous partons du besoin et concevons la pièce pour vous.'),
      ('Réalisez-vous des prototypes et des pièces unitaires ?', 'Oui. Nous fabriquons prototypes, pièces unitaires et pièces de rechange ainsi que des petites et moyennes séries ; chaque pièce est usinée et contrôlée dans notre atelier.'),
      ('Dans quelle langue pouvons-nous échanger ?', 'Notre équipe travaille en anglais et en roumain. Devis, plans et documents de livraison sont fournis en anglais ; vous pouvez nous écrire votre demande en français.')],
 faq_customs_q='Y a-t-il des droits de douane ou de la TVA sur les livraisons {to} ?',
 con_tag='Contact', con_title='Demander un devis',
 con_p='Envoyez-nous votre plan et votre besoin : nous revenons vers vous avec un prix et un délai de livraison {to}.',
 l_phone='Téléphone', l_addr='Adresse', romania='Roumanie',
 f_name='Nom', f_email='E-mail', f_company='Société (facultatif)', f_msg='Message – décrivez votre pièce ou votre projet',
 f_send='Envoyer la demande', f_sending='Envoi…', f_sent='✓ Envoyé – nous vous répondons rapidement.', f_error='✗ Erreur – veuillez réessayer', f_missing='Veuillez indiquer votre nom, votre e-mail et votre message.',
 more_tag='Europe', more_title='Nous livrons dans toute l’Europe', more_all='Tous les pays',
 bc_home='Accueil', bc_eu='Europe', bc_page='{N}',
 nav_home='Accueil', nav_services='Services', nav_contact='Contact', skip='Aller au contenu',
 foot='Usinage CNC et machines spéciales, Satu Mare, Roumanie',
)

# --------------------------------------------------------------- ITALIANO
L['it'] = dict(
 code='it', kw='Lavorazioni CNC', svc_name='Lavorazioni meccaniche CNC e macchine speciali per {n}',
 title='Lavorazioni CNC conto terzi per {n} | DajbocTechDon, Romania',
 desc='Tornitura e fresatura CNC, macchine speciali e componenti metallici prodotti in Romania e consegnati {to} in {days} giorni lavorativi. Prototipi e serie: richiedi un preventivo.',
 h1='Lavorazioni meccaniche CNC &amp; macchine speciali <span class="gt">per le aziende {in}</span>',
 badge='Prodotto in Romania · consegna {to}',
 lead='DajbocTechDon S.R.L. realizza componenti metallici di precisione con macchine CNC e progetta e costruisce macchine speciali nella propria officina di Satu Mare, in Romania. Forniamo alle aziende {in} prototipi, pezzi singoli, ricambi e piccole e medie serie – dal vostro disegno fino alla consegna.',
 cta_quote='Richiedi un preventivo', cta_services='I nostri servizi',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km in linea d’aria',
 f_transit='Trasporto su strada (indicativo)', f_transit_v='{days} giorni lavorativi',
 f_customs='Dogana', f_quote='Preventivi', f_quote_v='in EUR · inglese',
 customs_short=dict(eu='Nessuna – mercato unico UE', cu='Unione doganale UE'),
 customs_long=dict(
  eu='Come la Romania, {nom} è membro dell’Unione europea: nessuna formalità doganale e nessun dazio. Le forniture ad aziende con partita IVA comunitaria valida sono fatturate come cessioni intracomunitarie senza IVA rumena (inversione contabile / reverse charge).',
  cu='{nom} forma un’unione doganale con l’Unione europea: sui prodotti industriali non si applicano dazi, ma non fa parte del sistema IVA dell’UE. Prepariamo i documenti di esportazione; l’imposta all’importazione viene assolta {in} secondo le norme locali.'),
 svc_tag='Cosa facciamo', svc_title='Lavorazioni CNC e ingegneria per {n}',
 svc_intro='Un unico fornitore per tutta la filiera – dai primi requisiti al prodotto finito e collaudato, consegnato {to}.',
 svc=[('Requisiti e ingegneria', 'Definiamo con voi obiettivi, specifiche, tolleranze, materiali e quantità prima di iniziare la progettazione.'),
      ('Progettazione meccanica', 'Progettazione di componenti, attrezzature e macchine speciali per automotive, industria, agricoltura ed energia.'),
      ('Simulazione', 'Verifica di capacità di carico, conformità e funzionamento del progetto prima della produzione.'),
      ('Tornitura e fresatura CNC', 'Lavorazione CNC di precisione di componenti metallici in officina – dal prototipo alla serie.'),
      ('Assemblaggio', 'Montaggio di parti lavorate e acquistate in gruppi completi e funzionanti.'),
      ('Controllo della produzione', 'Gestione del processo e controllo qualità in ogni fase della produzione.'),
      ('Collaudo', 'Controlli dimensionali e funzionali per garantire sicurezza e prestazioni di ogni pezzo.'),
      ('Logistica e consegna', 'Imballaggio, documenti e trasporto fino al vostro stabilimento, in tutta Europa.')],
 ind_tag='Settori', ind_title='Settori che serviamo {in}',
 ind_intro='L’industria {in} è particolarmente forte in questi ambiti: {sectors}. Per le aziende di questi settori produciamo componenti, ricambi e macchine speciali:',
 ind=[('Automotive', 'Particolari torniti e fresati di precisione, attrezzature e gruppi per costruttori e fornitori.'),
      ('Industria e macchinari', 'Macchine speciali, attrezzature, dime e ricambi per linee di produzione e manutenzione.'),
      ('Agricoltura', 'Componenti e attrezzature per macchine agricole, costruiti per condizioni di lavoro difficili.'),
      ('Energia', 'Parti e gruppi per la produzione e le infrastrutture energetiche, sicuri e affidabili.')],
 why_tag='Perché la Romania', why_title='Perché un partner CNC in Romania?',
 why=['La Romania è nell’UE: norme europee, diritto contrattuale europeo e scambi semplici.',
      'Costi di produzione competitivi e un parco macchine CNC moderno.',
      'Tutto in un’unica officina: progettazione, simulazione, lavorazione, assemblaggio e collaudo.',
      'Prototipi, pezzi singoli, piccole e medie serie – senza grandi quantitativi minimi.',
      'Contatto diretto con gli ingegneri che realizzano i vostri pezzi.'],
 img_alt='Lavorazione CNC nell’officina DajbocTechDon a Satu Mare, Romania',
 how_tag='Come funziona', how_title='Dal disegno alla consegna in quattro passi',
 how=[('Inviate la richiesta', 'Disegno o modello 3D (PDF, STEP, IGES, DXF), materiale, quantità e data richiesta.'),
      ('Ricevete il preventivo', 'Verifichiamo la fattibilità e vi comunichiamo prezzo e tempi.'),
      ('Produzione', 'Lavorazione, assemblaggio e collaudo nella nostra officina, con controllo qualità a ogni passo.'),
      ('Consegna', 'Imballato, documentato e spedito al vostro indirizzo.')],
 log_tag='Logistica', log_title='Consegna {to}: tempi, dogana e IVA',
 log_p1='La nostra officina si trova a Turț, nel distretto di Satu Mare, nel nord-ovest della Romania – a circa {km} km in linea d’aria da {city}. I pezzi viaggiano su strada (groupage o camion dedicato) oppure con corriere espresso per piccoli pezzi urgenti; il tempo di transito tipico {to} è di {days} giorni lavorativi. Consegniamo ovunque {in}, anche nei distretti industriali come {hubs}.',
 log_p3='Le condizioni di resa (ad es. EXW, FCA o DAP vostro stabilimento) vengono concordate nel preventivo. I pezzi vengono puliti, protetti dalla corrosione se necessario e imballati per il trasporto; ogni spedizione è accompagnata dai documenti di consegna e, su richiesta, dai rapporti di controllo.',
 faq_title='Domande dei clienti {in}',
 faq=[('Consegnate pezzi lavorati CNC {to}?', 'Sì. Spediamo particolari lavorati, gruppi assemblati e macchine complete {to} su strada o con corriere. Il transito tipico da Satu Mare è di {days} giorni lavorativi, a seconda della destinazione e del tipo di trasporto.'),
      ('Cosa vi serve per un preventivo?', 'Un disegno tecnico o un modello 3D (PDF, STEP, IGES o DXF), il materiale, la quantità e la data di consegna desiderata. Se avete solo un campione o un’idea, partiamo dai requisiti e progettiamo il pezzo per voi.'),
      ('Realizzate prototipi e pezzi singoli?', 'Sì. Produciamo prototipi, pezzi singoli e ricambi oltre a piccole e medie serie; ogni pezzo viene lavorato e controllato nella nostra officina.'),
      ('In che lingua possiamo comunicare?', 'Il nostro team lavora in inglese e rumeno. Preventivi, disegni e documenti di consegna sono forniti in inglese; potete comunque scriverci la vostra richiesta in italiano.')],
 faq_customs_q='Ci sono dazi o IVA sulle consegne {to}?',
 con_tag='Contatti', con_title='Richiedi un preventivo',
 con_p='Inviateci disegno e requisiti: vi risponderemo con prezzo e tempi di consegna {to}.',
 l_phone='Telefono', l_addr='Indirizzo', romania='Romania',
 f_name='Nome', f_email='E-mail', f_company='Azienda (facoltativo)', f_msg='Messaggio – descrivete il pezzo o il progetto',
 f_send='Invia la richiesta', f_sending='Invio in corso…', f_sent='✓ Inviato – vi ricontatteremo a breve.', f_error='✗ Errore – riprovate', f_missing='Compilate nome, e-mail e messaggio.',
 more_tag='Europa', more_title='Consegniamo in tutta Europa', more_all='Tutti i paesi',
 bc_home='Home', bc_eu='Europa', bc_page='{N}',
 nav_home='Home', nav_services='Servizi', nav_contact='Contatti', skip='Vai al contenuto',
 foot='Lavorazioni CNC e macchine speciali, Satu Mare, Romania',
)

# --------------------------------------------------------------- ESPAÑOL
L['es'] = dict(
 code='es', kw='Mecanizado CNC', svc_name='Mecanizado CNC y maquinaria especial para {n}',
 title='Mecanizado CNC para {n} | Fabricante en Rumanía – DajbocTechDon',
 desc='Torneado y fresado CNC, maquinaria especial y piezas metálicas fabricadas en Rumanía y entregadas {to} en {days} días laborables. Prototipos y series: pida presupuesto.',
 h1='Mecanizado CNC y maquinaria especial <span class="gt">para empresas {in}</span>',
 badge='Fabricado en Rumanía · entrega {to}',
 lead='DajbocTechDon S.R.L. mecaniza piezas metálicas de precisión y diseña y fabrica maquinaria especial en su propio taller de Satu Mare, Rumanía. Suministramos a empresas {in} prototipos, piezas unitarias, recambios y series cortas y medias: desde su plano hasta la entrega.',
 cta_quote='Pedir presupuesto', cta_services='Nuestros servicios',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km en línea recta',
 f_transit='Transporte por carretera (orientativo)', f_transit_v='{days} días laborables',
 f_customs='Aduanas', f_quote='Presupuestos', f_quote_v='en EUR · inglés',
 customs_short=dict(eu='Ninguna – mercado único UE'),
 customs_long=dict(
  eu='Al igual que Rumanía, {nom} es miembro de la Unión Europea: sin trámites aduaneros ni aranceles. Las entregas a empresas con NIF-IVA intracomunitario válido se facturan como entregas intracomunitarias sin IVA rumano (inversión del sujeto pasivo).'),
 svc_tag='Qué hacemos', svc_title='Mecanizado CNC e ingeniería para {n}',
 svc_intro='Un único proveedor para toda la cadena: desde los primeros requisitos hasta el producto terminado y probado, entregado {to}.',
 svc=[('Requisitos e ingeniería', 'Definimos con usted objetivos, especificaciones, tolerancias, materiales y cantidades antes de diseñar.'),
      ('Diseño mecánico', 'Diseño de piezas, utillajes y maquinaria especial para automoción, industria, agricultura y energía.'),
      ('Simulación', 'Verificación de la capacidad de carga, la conformidad y el funcionamiento del diseño antes de fabricar.'),
      ('Torneado y fresado CNC', 'Mecanizado CNC de precisión de piezas metálicas en nuestro taller, del prototipo a la serie.'),
      ('Montaje', 'Montaje de piezas mecanizadas y compradas en conjuntos completos y funcionales.'),
      ('Control de producción', 'Gestión del proceso y control de calidad en cada fase de la fabricación.'),
      ('Ensayos', 'Controles dimensionales y funcionales para garantizar la seguridad y el rendimiento de cada pieza.'),
      ('Logística y entrega', 'Embalaje, documentación y transporte hasta su planta, en toda Europa.')],
 ind_tag='Sectores', ind_title='Sectores a los que servimos {in}',
 ind_intro='La industria {in} destaca especialmente en: {sectors}. Para las empresas de estos sectores fabricamos componentes, recambios y maquinaria especial:',
 ind=[('Automoción', 'Piezas torneadas y fresadas de precisión, utillajes y conjuntos para fabricantes y proveedores.'),
      ('Industria y maquinaria', 'Máquinas especiales, utillajes, plantillas y recambios para líneas de producción y mantenimiento.'),
      ('Agrícola', 'Componentes y equipos para maquinaria agrícola, preparados para condiciones de trabajo duras.'),
      ('Energía', 'Piezas y conjuntos para generación e infraestructuras energéticas, seguros y fiables.')],
 why_tag='Por qué Rumanía', why_title='¿Por qué un proveedor CNC en Rumanía?',
 why=['Rumanía es miembro de la UE: normas europeas, derecho contractual europeo y comercio sencillo.',
      'Costes de producción competitivos y maquinaria CNC moderna.',
      'Todo en un mismo taller: diseño, simulación, mecanizado, montaje y ensayos.',
      'Prototipos, piezas unitarias y series cortas o medias, sin grandes cantidades mínimas.',
      'Contacto directo con los ingenieros que fabrican sus piezas.'],
 img_alt='Mecanizado CNC en el taller de DajbocTechDon en Satu Mare, Rumanía',
 how_tag='Cómo trabajamos', how_title='Del plano a la entrega en cuatro pasos',
 how=[('Envíe su solicitud', 'Plano o modelo 3D (PDF, STEP, IGES, DXF), material, cantidad y fecha deseada.'),
      ('Reciba el presupuesto', 'Comprobamos la viabilidad y le indicamos precio y plazo.'),
      ('Fabricación', 'Mecanizado, montaje y ensayos en nuestro taller, con control de calidad en cada paso.'),
      ('Entrega', 'Embalado, documentado y enviado a su dirección.')],
 log_tag='Logística', log_title='Entregas {to}: plazos, aduanas e IVA',
 log_p1='Nuestro taller está en Turț, provincia de Satu Mare, en el noroeste de Rumanía, a unos {km} km en línea recta de {city}. Las piezas viajan por carretera (grupaje o camión completo) o por mensajería urgente en el caso de piezas pequeñas; el tránsito habitual {to} es de {days} días laborables. Entregamos en cualquier punto {in}, incluidas zonas industriales como {hubs}.',
 log_p3='Las condiciones de entrega (por ejemplo EXW, FCA o DAP en su planta) se fijan en el presupuesto. Las piezas se limpian, se protegen contra la corrosión si es necesario y se embalan para el transporte; cada envío incluye la documentación de entrega y, bajo petición, los informes de control.',
 faq_title='Preguntas de clientes {in}',
 faq=[('¿Entregan piezas mecanizadas {to}?', 'Sí. Enviamos piezas mecanizadas, conjuntos y máquinas completas {to} por carretera o mensajería. El tránsito habitual desde Satu Mare es de {days} días laborables, según el destino y el tipo de transporte.'),
      ('¿Qué necesitan para preparar un presupuesto?', 'Un plano técnico o modelo 3D (PDF, STEP, IGES o DXF), el material, la cantidad y la fecha de entrega deseada. Si solo tiene una muestra o una idea, partimos de los requisitos y diseñamos la pieza para usted.'),
      ('¿Fabrican prototipos y piezas unitarias?', 'Sí. Fabricamos prototipos, piezas unitarias y recambios, además de series cortas y medias; cada pieza se mecaniza y controla en nuestro propio taller.'),
      ('¿En qué idioma podemos comunicarnos?', 'Nuestro equipo trabaja en inglés y rumano. Presupuestos, planos y documentos de entrega se facilitan en inglés; puede enviarnos su consulta en español.')],
 faq_customs_q='¿Hay aranceles o IVA en las entregas {to}?',
 con_tag='Contacto', con_title='Pida su presupuesto',
 con_p='Envíenos su plano y sus requisitos y le responderemos con precio y plazo de entrega {to}.',
 l_phone='Teléfono', l_addr='Dirección', romania='Rumanía',
 f_name='Nombre', f_email='Correo electrónico', f_company='Empresa (opcional)', f_msg='Mensaje – describa su pieza o proyecto',
 f_send='Enviar solicitud', f_sending='Enviando…', f_sent='✓ Enviado – le responderemos en breve.', f_error='✗ Error – inténtelo de nuevo', f_missing='Indique su nombre, correo y mensaje.',
 more_tag='Europa', more_title='Entregamos en toda Europa', more_all='Todos los países',
 bc_home='Inicio', bc_eu='Europa', bc_page='{N}',
 nav_home='Inicio', nav_services='Servicios', nav_contact='Contacto', skip='Ir al contenido',
 foot='Mecanizado CNC y maquinaria especial, Satu Mare, Rumanía',
)

# --------------------------------------------------------------- CATALÀ (Andorra)
L['ca'] = dict(
 code='ca', kw='Mecanitzat CNC', svc_name='Mecanitzat CNC i maquinària especial per a {n}',
 title='Mecanitzat CNC per a {n} | Fabricant a Romania – DajbocTechDon',
 desc='Tornejat i fresat CNC, maquinària especial i peces metàl·liques fabricades a Romania i lliurades {to} en {days} dies laborables. Prototips i sèries: demaneu pressupost.',
 h1='Mecanitzat CNC i maquinària especial <span class="gt">per a empreses {in}</span>',
 badge='Fabricat a Romania · lliurament {to}',
 lead='DajbocTechDon S.R.L. mecanitza peces metàl·liques de precisió i dissenya i fabrica maquinària especial al seu propi taller de Satu Mare, Romania. Subministrem a empreses {in} prototips, peces unitàries, recanvis i sèries curtes i mitjanes: des del vostre plànol fins al lliurament.',
 cta_quote='Demanar pressupost', cta_services='Els nostres serveis',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km en línia recta',
 f_transit='Transport per carretera (orientatiu)', f_transit_v='{days} dies laborables',
 f_customs='Duanes', f_quote='Pressupostos', f_quote_v='en EUR · anglès',
 customs_short=dict(cu='Unió duanera amb la UE'),
 customs_long=dict(
  cu='{nom} té una unió duanera amb la Unió Europea per als productes industrials, que per tant no paguen aranzels, però no forma part del sistema d’IVA de la UE. Preparem la documentació d’exportació; l’impost indirecte a la importació es liquida {in} segons la normativa local.'),
 svc_tag='Què fem', svc_title='Mecanitzat CNC i enginyeria per a {n}',
 svc_intro='Un sol proveïdor per a tota la cadena: des dels primers requisits fins al producte acabat i provat, lliurat {to}.',
 svc=[('Requisits i enginyeria', 'Definim amb vosaltres objectius, especificacions, toleràncies, materials i quantitats abans de dissenyar.'),
      ('Disseny mecànic', 'Disseny de peces, utillatges i maquinària especial per a automoció, indústria, agricultura i energia.'),
      ('Simulació', 'Verificació de la capacitat de càrrega, la conformitat i el funcionament del disseny abans de fabricar.'),
      ('Tornejat i fresat CNC', 'Mecanitzat CNC de precisió de peces metàl·liques al nostre taller, del prototip a la sèrie.'),
      ('Muntatge', 'Muntatge de peces mecanitzades i comprades en conjunts complets i funcionals.'),
      ('Control de producció', 'Gestió del procés i control de qualitat a cada fase de la fabricació.'),
      ('Assaigs', 'Controls dimensionals i funcionals per garantir la seguretat i el rendiment de cada peça.'),
      ('Logística i lliurament', 'Embalatge, documentació i transport fins a la vostra planta, a tot Europa.')],
 ind_tag='Sectors', ind_title='Sectors que servim {in}',
 ind_intro='L’economia {in} destaca en: {sectors}. Per a empreses i serveis tècnics d’aquests àmbits fabriquem components, recanvis i maquinària especial:',
 ind=[('Automoció', 'Peces tornejades i fresades de precisió, utillatges i conjunts per a fabricants i proveïdors.'),
      ('Indústria i maquinària', 'Màquines especials, utillatges i recanvis per a producció i manteniment.'),
      ('Agrícola', 'Components i equips per a maquinària agrícola, preparats per a condicions dures.'),
      ('Energia', 'Peces i conjunts per a la generació i les infraestructures energètiques, segurs i fiables.')],
 why_tag='Per què Romania', why_title='Per què un proveïdor CNC a Romania?',
 why=['Romania és membre de la UE: normes europees i comerç senzill amb tot el continent.',
      'Costos de producció competitius i maquinària CNC moderna.',
      'Tot en un mateix taller: disseny, simulació, mecanitzat, muntatge i assaigs.',
      'Prototips, peces unitàries i sèries curtes o mitjanes, sense grans quantitats mínimes.',
      'Contacte directe amb els enginyers que fabriquen les vostres peces.'],
 img_alt='Mecanitzat CNC al taller de DajbocTechDon a Satu Mare, Romania',
 how_tag='Com treballem', how_title='Del plànol al lliurament en quatre passos',
 how=[('Envieu la sol·licitud', 'Plànol o model 3D (PDF, STEP, IGES, DXF), material, quantitat i data desitjada.'),
      ('Rebeu el pressupost', 'Comprovem la viabilitat i us indiquem preu i termini.'),
      ('Fabricació', 'Mecanitzat, muntatge i assaigs al nostre taller, amb control de qualitat a cada pas.'),
      ('Lliurament', 'Embalat, documentat i enviat a la vostra adreça.')],
 log_tag='Logística', log_title='Lliuraments {to}: terminis, duanes i impostos',
 log_p1='El nostre taller és a Turț, al districte de Satu Mare, al nord-oest de Romania, a uns {km} km en línia recta de {city}. Les peces viatgen per carretera (grupatge o camió complet) o per missatgeria urgent en el cas de peces petites; el trànsit habitual {to} és de {days} dies laborables. Lliurem a tot el país, incloent {hubs}.',
 log_p3='Les condicions de lliurament (per exemple EXW, FCA o DAP a la vostra adreça) es fixen al pressupost. Les peces es netegen, es protegeixen contra la corrosió si cal i s’embalen per al transport; cada enviament inclou la documentació de lliurament i, a petició, els informes de control.',
 faq_title='Preguntes de clients {in}',
 faq=[('Lliureu peces mecanitzades {to}?', 'Sí. Enviem peces mecanitzades, conjunts i màquines completes {to} per carretera o missatgeria. El trànsit habitual des de Satu Mare és de {days} dies laborables, segons el tipus de transport.'),
      ('Què necessiteu per preparar un pressupost?', 'Un plànol tècnic o model 3D (PDF, STEP, IGES o DXF), el material, la quantitat i la data de lliurament desitjada. Si només teniu una mostra o una idea, partim dels requisits i dissenyem la peça.'),
      ('Fabriqueu prototips i peces unitàries?', 'Sí. Fabriquem prototips, peces unitàries i recanvis, a més de sèries curtes i mitjanes; cada peça es mecanitza i es controla al nostre taller.'),
      ('En quina llengua ens podem comunicar?', 'El nostre equip treballa en anglès i romanès. Pressupostos, plànols i documents de lliurament es faciliten en anglès; podeu escriure’ns la consulta en català o castellà.')],
 faq_customs_q='Hi ha aranzels o impostos en els lliuraments {to}?',
 con_tag='Contacte', con_title='Demaneu pressupost',
 con_p='Envieu-nos el plànol i els requisits i us respondrem amb preu i termini de lliurament {to}.',
 l_phone='Telèfon', l_addr='Adreça', romania='Romania',
 f_name='Nom', f_email='Correu electrònic', f_company='Empresa (opcional)', f_msg='Missatge – descriviu la peça o el projecte',
 f_send='Enviar sol·licitud', f_sending='Enviant…', f_sent='✓ Enviat – us respondrem aviat.', f_error='✗ Error – torneu-ho a provar', f_missing='Indiqueu el nom, el correu i el missatge.',
 more_tag='Europa', more_title='Lliurem a tot Europa', more_all='Tots els països',
 bc_home='Inici', bc_eu='Europa', bc_page='{N}',
 nav_home='Inici', nav_services='Serveis', nav_contact='Contacte', skip='Anar al contingut',
 foot='Mecanitzat CNC i maquinària especial, Satu Mare, Romania',
)

# --------------------------------------------------------------- PORTUGUÊS (PT)
L['pt'] = dict(
 code='pt', kw='Maquinação CNC', svc_name='Maquinação CNC e máquinas especiais para {n}',
 title='Maquinação CNC para {n} | Fabricante na Roménia – DajbocTechDon',
 desc='Torneamento e fresagem CNC, máquinas especiais e peças metálicas produzidas na Roménia e entregues {to} em {days} dias úteis. Protótipos e séries – peça orçamento.',
 h1='Maquinação CNC e máquinas especiais <span class="gt">para empresas {in}</span>',
 badge='Fabricado na Roménia · entrega {to}',
 lead='A DajbocTechDon S.R.L. maquina peças metálicas de precisão e projeta e constrói máquinas especiais na sua própria oficina em Satu Mare, na Roménia. Fornecemos às empresas {in} protótipos, peças unitárias, peças de substituição e pequenas e médias séries – do seu desenho até à entrega.',
 cta_quote='Pedir orçamento', cta_services='Os nossos serviços',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km em linha reta',
 f_transit='Transporte rodoviário (indicativo)', f_transit_v='{days} dias úteis',
 f_customs='Alfândega', f_quote='Orçamentos', f_quote_v='em EUR · inglês',
 customs_short=dict(eu='Nenhuma – mercado único UE'),
 customs_long=dict(
  eu='Tal como a Roménia, {nom} é membro da União Europeia: sem formalidades aduaneiras nem direitos. As entregas a empresas com número de IVA intracomunitário válido são faturadas como transmissões intracomunitárias, sem IVA romeno (autoliquidação).'),
 svc_tag='O que fazemos', svc_title='Maquinação CNC e engenharia para {n}',
 svc_intro='Um único fornecedor para toda a cadeia – dos primeiros requisitos ao produto acabado e testado, entregue {to}.',
 svc=[('Requisitos e engenharia', 'Definimos consigo objetivos, especificações, tolerâncias, materiais e quantidades antes de projetar.'),
      ('Projeto mecânico', 'Projeto de peças, ferramentas e máquinas especiais para os setores automóvel, industrial, agrícola e energético.'),
      ('Simulação', 'Verificação da capacidade de carga, conformidade e funcionamento do projeto antes da produção.'),
      ('Torneamento e fresagem CNC', 'Maquinação CNC de precisão de peças metálicas na nossa oficina – do protótipo à série.'),
      ('Montagem', 'Montagem de peças maquinadas e adquiridas em conjuntos completos e funcionais.'),
      ('Controlo da produção', 'Gestão do processo e controlo de qualidade em cada fase da produção.'),
      ('Ensaios', 'Controlos dimensionais e funcionais para garantir a segurança e o desempenho de cada peça.'),
      ('Logística e entrega', 'Embalagem, documentação e transporte até às suas instalações, em toda a Europa.')],
 ind_tag='Setores', ind_title='Setores que servimos {in}',
 ind_intro='A indústria {in} destaca-se sobretudo em: {sectors}. Para as empresas destes setores produzimos componentes, peças de substituição e máquinas especiais:',
 ind=[('Automóvel', 'Peças torneadas e fresadas de precisão, ferramentas e conjuntos para fabricantes e fornecedores.'),
      ('Indústria e máquinas', 'Máquinas especiais, dispositivos, gabaritos e peças para linhas de produção e manutenção.'),
      ('Agrícola', 'Componentes e equipamentos para máquinas agrícolas, preparados para condições exigentes.'),
      ('Energia', 'Peças e conjuntos para produção e infraestruturas de energia, seguros e fiáveis.')],
 why_tag='Porquê a Roménia', why_title='Porquê um parceiro CNC na Roménia?',
 why=['A Roménia é membro da UE: normas europeias, direito contratual europeu e comércio simples.',
      'Custos de produção competitivos e equipamento CNC moderno.',
      'Tudo na mesma oficina: projeto, simulação, maquinação, montagem e ensaios.',
      'Protótipos, peças unitárias e pequenas ou médias séries – sem grandes quantidades mínimas.',
      'Contacto direto com os engenheiros que fabricam as suas peças.'],
 img_alt='Maquinação CNC na oficina da DajbocTechDon em Satu Mare, Roménia',
 how_tag='Como funciona', how_title='Do desenho à entrega em quatro passos',
 how=[('Envie o pedido', 'Desenho ou modelo 3D (PDF, STEP, IGES, DXF), material, quantidade e data pretendida.'),
      ('Receba o orçamento', 'Verificamos a viabilidade e indicamos preço e prazo.'),
      ('Produção', 'Maquinação, montagem e ensaios na nossa oficina, com controlo de qualidade em cada etapa.'),
      ('Entrega', 'Embalado, documentado e enviado para a sua morada.')],
 log_tag='Logística', log_title='Entregas {to}: prazos, alfândega e IVA',
 log_p1='A nossa oficina fica em Turț, distrito de Satu Mare, no noroeste da Roménia – a cerca de {km} km em linha reta de {city}. As peças seguem por via rodoviária (grupagem ou camião dedicado) ou por correio expresso no caso de peças pequenas e urgentes; o trânsito habitual {to} é de {days} dias úteis. Entregamos em qualquer ponto do país, incluindo zonas industriais como {hubs}.',
 log_p3='As condições de entrega (por exemplo EXW, FCA ou DAP nas suas instalações) são definidas no orçamento. As peças são limpas, protegidas contra a corrosão quando necessário e embaladas para transporte; cada envio segue com os documentos de entrega e, a pedido, relatórios de controlo.',
 faq_title='Perguntas de clientes {in}',
 faq=[('Entregam peças maquinadas {to}?', 'Sim. Enviamos peças maquinadas, conjuntos e máquinas completas {to} por via rodoviária ou correio expresso. O trânsito habitual a partir de Satu Mare é de {days} dias úteis, conforme o destino e o modo de transporte.'),
      ('De que precisam para um orçamento?', 'De um desenho técnico ou modelo 3D (PDF, STEP, IGES ou DXF), do material, da quantidade e da data de entrega pretendida. Se tiver apenas uma amostra ou uma ideia, partimos dos requisitos e projetamos a peça.'),
      ('Fazem protótipos e peças unitárias?', 'Sim. Produzimos protótipos, peças unitárias e peças de substituição, bem como pequenas e médias séries; cada peça é maquinada e controlada na nossa oficina.'),
      ('Em que língua podemos comunicar?', 'A nossa equipa trabalha em inglês e romeno. Orçamentos, desenhos e documentos de entrega são fornecidos em inglês; pode enviar-nos o seu pedido em português.')],
 faq_customs_q='Há direitos aduaneiros ou IVA nas entregas {to}?',
 con_tag='Contacto', con_title='Peça um orçamento',
 con_p='Envie-nos o desenho e os requisitos e responderemos com preço e prazo de entrega {to}.',
 l_phone='Telefone', l_addr='Morada', romania='Roménia',
 f_name='Nome', f_email='E-mail', f_company='Empresa (opcional)', f_msg='Mensagem – descreva a peça ou o projeto',
 f_send='Enviar pedido', f_sending='A enviar…', f_sent='✓ Enviado – entraremos em contacto em breve.', f_error='✗ Erro – tente novamente', f_missing='Preencha o nome, o e-mail e a mensagem.',
 more_tag='Europa', more_title='Entregamos em toda a Europa', more_all='Todos os países',
 bc_home='Início', bc_eu='Europa', bc_page='{N}',
 nav_home='Início', nav_services='Serviços', nav_contact='Contacto', skip='Saltar para o conteúdo',
 foot='Maquinação CNC e máquinas especiais, Satu Mare, Roménia',
)

# --------------------------------------------------------------- NEDERLANDS
L['nl'] = dict(
 code='nl', kw='CNC-verspaning', svc_name='CNC-verspaning en speciale machinebouw voor {n}',
 title='CNC-verspaning voor {n} | Toeleverancier uit Roemenië – DajbocTechDon',
 desc='CNC-draaien en -frezen, speciale machines en metalen onderdelen uit Roemenië, geleverd {to} in {days} werkdagen. Prototypes en series – vraag een offerte aan.',
 h1='CNC-verspaning &amp; speciale machinebouw <span class="gt">voor bedrijven {in}</span>',
 badge='Made in Romania · levering {to}',
 lead='DajbocTechDon S.R.L. verspaant precisie-onderdelen van metaal en ontwerpt en bouwt speciale machines in de eigen werkplaats in Satu Mare, Roemenië. Wij leveren bedrijven {in} prototypes, enkelstuks, reserveonderdelen en kleine en middelgrote series – van uw tekening tot de levering.',
 cta_quote='Offerte aanvragen', cta_services='Onze diensten',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km hemelsbreed',
 f_transit='Wegtransport (indicatief)', f_transit_v='{days} werkdagen',
 f_customs='Douane', f_quote='Offertes', f_quote_v='in EUR · Engels',
 customs_short=dict(eu='Geen – EU-interne markt'),
 customs_long=dict(
  eu='Net als Roemenië is {n} lid van de Europese Unie: geen douaneformaliteiten en geen invoerrechten. Leveringen aan bedrijven met een geldig EU-btw-nummer factureren wij als intracommunautaire levering zonder Roemeense btw (btw verlegd).'),
 svc_tag='Wat we doen', svc_title='CNC-verspaning en engineering voor {n}',
 svc_intro='Eén leverancier voor de hele keten – van de eerste eisen tot het afgewerkte, geteste product, geleverd {to}.',
 svc=[('Eisen & engineering', 'We bepalen samen met u doelen, specificaties, toleranties, materialen en aantallen voordat het ontwerp begint.'),
      ('Mechanisch ontwerp', 'Ontwerp van onderdelen, mallen en speciale machines voor automotive, industrie, landbouw en energie.'),
      ('Simulatie', 'Controle van draagvermogen, conformiteit en werking van het ontwerp vóór de productie.'),
      ('CNC-draaien & -frezen', 'Precisieverspaning van metalen onderdelen in eigen huis – van prototype tot serie.'),
      ('Assemblage', 'Montage van verspaande en ingekochte delen tot complete, werkende eenheden.'),
      ('Productiebeheersing', 'Procesbeheer en kwaliteitscontrole in elke fase van de productie.'),
      ('Testen', 'Maat- en functiecontroles zodat elk onderdeel voldoet aan de eisen voor veiligheid en prestaties.'),
      ('Logistiek & levering', 'Verpakking, documenten en transport tot aan uw bedrijf, overal in Europa.')],
 ind_tag='Sectoren', ind_title='Sectoren die we {in} bedienen',
 ind_intro='De industrie {in} is vooral sterk in: {sectors}. Voor bedrijven in deze sectoren maken wij onderdelen, reserveonderdelen en speciale machines:',
 ind=[('Automotive', 'Precisiedraai- en freesdelen, mallen en assemblages voor voertuigbouwers en toeleveranciers.'),
      ('Industrie & machinebouw', 'Speciale machines, opspanmiddelen, mallen en reserveonderdelen voor productie en onderhoud.'),
      ('Landbouw', 'Componenten en uitrusting voor landbouwmachines, gebouwd voor zware omstandigheden.'),
      ('Energie', 'Onderdelen en assemblages voor energieopwekking en -infrastructuur, veilig en betrouwbaar.')],
 why_tag='Waarom Roemenië', why_title='Waarom een CNC-partner in Roemenië?',
 why=['Roemenië is lid van de EU – Europese normen, Europees contractrecht en eenvoudige handel.',
      'Concurrerende productiekosten en een modern CNC-machinepark.',
      'Alles in één werkplaats: ontwerp, simulatie, verspaning, assemblage en testen.',
      'Prototypes, enkelstuks en kleine of middelgrote series – geen hoge minimale aantallen.',
      'Direct contact met de engineers die uw onderdelen maken.'],
 img_alt='CNC-verspaning in de werkplaats van DajbocTechDon in Satu Mare, Roemenië',
 how_tag='Werkwijze', how_title='Van tekening tot levering in vier stappen',
 how=[('Stuur uw aanvraag', 'Tekening of 3D-model (PDF, STEP, IGES, DXF), materiaal, aantal en gewenste datum.'),
      ('Ontvang een offerte', 'We controleren de haalbaarheid en geven prijs en levertijd door.'),
      ('Productie', 'Verspaning, assemblage en testen in onze werkplaats, met kwaliteitscontrole bij elke stap.'),
      ('Levering', 'Verpakt, gedocumenteerd en verzonden naar uw adres.')],
 log_tag='Logistiek', log_title='Levering {to}: levertijden, douane en btw',
 log_p1='Onze werkplaats ligt in Turț, district Satu Mare, in het noordwesten van Roemenië – hemelsbreed zo’n {km} km van {city}. Onderdelen gaan over de weg (groupage of eigen vracht) of per expreskoerier voor kleine spoeddelen; de gebruikelijke transittijd {to} is {days} werkdagen. We leveren overal {in}, ook in industriegebieden zoals {hubs}.',
 log_p3='De leveringsvoorwaarden (bijvoorbeeld EXW, FCA of DAP uw fabriek) worden in de offerte vastgelegd. Onderdelen worden gereinigd, indien nodig geconserveerd en transportklaar verpakt; elke zending gaat vergezeld van de leveringsdocumenten en op verzoek van meetrapporten.',
 faq_title='Vragen van klanten {in}',
 faq=[('Leveren jullie CNC-onderdelen {to}?', 'Ja. We versturen draai- en freesdelen, assemblages en complete machines {to} per vrachtwagen of koerier. De gebruikelijke transittijd vanaf Satu Mare is {days} werkdagen, afhankelijk van bestemming en vervoerswijze.'),
      ('Wat hebben jullie nodig voor een offerte?', 'Een technische tekening of 3D-model (PDF, STEP, IGES of DXF), het materiaal, het aantal en de gewenste leverdatum. Heeft u alleen een monster of een idee, dan beginnen we bij de eisen en ontwerpen we het onderdeel voor u.'),
      ('Maken jullie prototypes en enkelstuks?', 'Ja. We maken prototypes, enkelstuks en reserveonderdelen, maar ook kleine en middelgrote series; elk onderdeel wordt in onze eigen werkplaats verspaand en gecontroleerd.'),
      ('In welke taal kunnen we communiceren?', 'Ons team werkt in het Engels en Roemeens. Offertes, tekeningen en leveringsdocumenten zijn in het Engels; uw aanvraag mag u ook in het Nederlands sturen.')],
 faq_customs_q='Zijn er invoerrechten of btw bij leveringen {to}?',
 con_tag='Contact', con_title='Vraag een offerte aan',
 con_p='Stuur ons uw tekening en eisen – u ontvangt prijs en levertijd voor levering {to}.',
 l_phone='Telefoon', l_addr='Adres', romania='Roemenië',
 f_name='Naam', f_email='E-mail', f_company='Bedrijf (optioneel)', f_msg='Bericht – beschrijf uw onderdeel of project',
 f_send='Aanvraag versturen', f_sending='Versturen…', f_sent='✓ Verzonden – we nemen snel contact op.', f_error='✗ Fout – probeer opnieuw', f_missing='Vul uw naam, e-mail en bericht in.',
 more_tag='Europa', more_title='Wij leveren in heel Europa', more_all='Alle landen',
 bc_home='Home', bc_eu='Europa', bc_page='{N}',
 nav_home='Home', nav_services='Diensten', nav_contact='Contact', skip='Naar de inhoud',
 foot='CNC-verspaning en speciale machinebouw, Satu Mare, Roemenië',
)
