# -*- coding: utf-8 -*-
# Testi delle landing page per paese — Paesi nordici e baltici.
L = {}

# --------------------------------------------------------------- SVENSKA
L['sv'] = dict(
 code='sv', kw='CNC-bearbetning', svc_name='CNC-bearbetning och specialmaskiner för företag {in}',
 title='CNC-bearbetning för företag {in} | Tillverkare i Rumänien – DajbocTechDon',
 desc='CNC-svarvning och fräsning, specialmaskiner och metalldetaljer tillverkade i Rumänien och levererade {to} på {days} arbetsdagar. Prototyper och serier – begär offert.',
 h1='CNC-bearbetning och specialmaskiner <span class="gt">för företag {in}</span>',
 badge='Tillverkat i Rumänien · leverans {to}',
 lead='DajbocTechDon S.R.L. tillverkar precisionsdetaljer i metall i CNC-maskiner och konstruerar och bygger specialmaskiner i egen verkstad i Satu Mare, Rumänien. Vi levererar prototyper, enstaka detaljer, reservdelar samt små och medelstora serier till företag {in} – från er ritning till leverans.',
 cta_quote='Begär offert', cta_services='Våra tjänster',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km fågelvägen',
 f_transit='Vägtransport (riktvärde)', f_transit_v='{days} arbetsdagar',
 f_customs='Tull', f_quote='Offerter', f_quote_v='i EUR · på engelska',
 customs_short=dict(eu='Ingen – EU:s inre marknad'),
 customs_long=dict(eu='{nom} är liksom Rumänien medlem i Europeiska unionen: inga tullformaliteter och inga tullar. Leveranser till företag med giltigt EU-momsregistreringsnummer faktureras som gemenskapsintern leverans utan rumänsk moms (omvänd skattskyldighet).'),
 svc_tag='Det här gör vi', svc_title='CNC-bearbetning och konstruktion för företag {in}',
 svc_intro='En leverantör för hela kedjan – från de första kraven till en färdig, testad produkt levererad {to}.',
 svc=[('Krav och konstruktion', 'Vi klargör mål, specifikationer, toleranser, material och antal tillsammans med er innan konstruktionen börjar.'),
      ('Maskinkonstruktion', 'Konstruktion av detaljer, fixturer och specialmaskiner för fordon, industri, jordbruk och energi.'),
      ('Simulering', 'Kontroll av hållfasthet, överensstämmelse och funktion innan tillverkningen startar.'),
      ('CNC-svarvning och fräsning', 'Precisionsbearbetning av metalldetaljer i egen verkstad – från prototyp till serie.'),
      ('Montering', 'Montering av bearbetade och inköpta delar till kompletta, fungerande enheter.'),
      ('Produktionsstyrning', 'Processtyrning och kvalitetskontroll i varje steg av tillverkningen.'),
      ('Provning', 'Mått- och funktionskontroll så att varje detalj uppfyller krav på säkerhet och prestanda.'),
      ('Logistik och leverans', 'Emballering, dokument och transport ända fram till er anläggning, i hela Europa.')],
 ind_tag='Branscher', ind_title='Branscher vi betjänar {in}',
 ind_intro='Industrin {in} är särskilt stark inom: {sectors}. Till företag i dessa branscher tillverkar vi komponenter, reservdelar och specialmaskiner:',
 ind=[('Fordonsindustri', 'Svarvade och frästa precisionsdetaljer, fixturer och delmonteringar för tillverkare och underleverantörer.'),
      ('Industri och maskiner', 'Specialmaskiner, fixturer, mätdon och reservdelar för produktionslinjer och underhåll.'),
      ('Jordbruk', 'Komponenter och utrustning för jordbruksmaskiner, byggda för tuffa förhållanden.'),
      ('Energi', 'Delar och enheter för energiproduktion och energiinfrastruktur – säkra och tillförlitliga.')],
 why_tag='Varför Rumänien', why_title='Varför en CNC-partner i Rumänien?',
 why=['Rumänien är EU-medlem – europeiska standarder, europeisk avtalsrätt och enkel handel.',
      'Konkurrenskraftiga tillverkningskostnader och moderna CNC-maskiner.',
      'Allt i en verkstad: konstruktion, simulering, bearbetning, montering och provning.',
      'Prototyper, enstaka detaljer, små och medelstora serier – inga höga minimikvantiteter.',
      'Direktkontakt med ingenjörerna som tillverkar era detaljer.'],
 img_alt='CNC-bearbetning i DajbocTechDons verkstad i Satu Mare, Rumänien',
 how_tag='Så fungerar det', how_title='Från ritning till leverans i fyra steg',
 how=[('Skicka förfrågan', 'Ritning eller 3D-modell (PDF, STEP, IGES, DXF), material, antal och önskat datum.'),
      ('Få offert', 'Vi kontrollerar genomförbarheten och lämnar pris och leveranstid.'),
      ('Tillverkning', 'Bearbetning, montering och provning i vår verkstad med kvalitetskontroll i varje steg.'),
      ('Leverans', 'Emballerat, dokumenterat och skickat till er adress.')],
 log_tag='Logistik', log_title='Leverans {to}: transittider, tull och moms',
 log_p1='Vår verkstad ligger i Turț i länet Satu Mare i nordvästra Rumänien – cirka {km} km fågelvägen från {city}. Detaljer skickas med lastbil (samlast eller hel bil) eller med expressbud för små brådskande delar; normal transittid {to} är {days} arbetsdagar. Vi levererar till hela landet, även till industriregioner som {hubs}.',
 log_p3='Leveransvillkoren (t.ex. EXW, FCA eller DAP er fabrik) fastställs i offerten. Detaljerna rengörs, korrosionsskyddas vid behov och packas för transport; varje sändning åtföljs av leveransdokument och på begäran av kontrollrapporter.',
 faq_title='Frågor från kunder {in}',
 faq=[('Levererar ni CNC-detaljer {to}?', 'Ja. Vi skickar svarvade och frästa detaljer, delmonteringar och kompletta maskiner {to} med lastbil eller bud. Normal transittid från Satu Mare är {days} arbetsdagar, beroende på destination och transportsätt.'),
      ('Vad behöver ni för en offert?', 'En teknisk ritning eller 3D-modell (PDF, STEP, IGES eller DXF), material, antal och önskat leveransdatum. Har ni bara ett prov eller en idé utgår vi från kraven och konstruerar detaljen åt er.'),
      ('Tillverkar ni prototyper och enstaka detaljer?', 'Ja. Vi tillverkar prototyper, enstaka detaljer och reservdelar samt små och medelstora serier; varje detalj bearbetas och kontrolleras i vår egen verkstad.'),
      ('Vilket språk kan vi kommunicera på?', 'Vårt team arbetar på engelska och rumänska. Offerter, ritningar och leveransdokument får ni på engelska; er förfrågan kan ni gärna skicka på svenska.')],
 faq_customs_q='Tillkommer tull eller moms vid leveranser {to}?',
 con_tag='Kontakt', con_title='Begär offert',
 con_p='Skicka er ritning och era krav – vi återkommer med pris och leveranstid {to}.',
 l_phone='Telefon', l_addr='Adress', romania='Rumänien',
 f_name='Namn', f_email='E-post', f_company='Företag (valfritt)', f_msg='Meddelande – beskriv detaljen eller projektet',
 f_send='Skicka förfrågan', f_sending='Skickar…', f_sent='✓ Skickat – vi hör av oss snart.', f_error='✗ Fel – försök igen', f_missing='Fyll i namn, e-post och meddelande.',
 more_tag='Europa', more_title='Vi levererar i hela Europa', more_all='Alla länder',
 bc_home='Hem', bc_eu='Europa', bc_page='{N}',
 nav_home='Hem', nav_services='Tjänster', nav_contact='Kontakt', skip='Till innehållet',
 foot='CNC-bearbetning och specialmaskiner, Satu Mare, Rumänien',
)

# --------------------------------------------------------------- DANSK
L['da'] = dict(
 code='da', kw='CNC-bearbejdning', svc_name='CNC-bearbejdning og specialmaskiner til virksomheder {in}',
 title='CNC-bearbejdning til virksomheder {in} | Producent i Rumænien – DajbocTechDon',
 desc='CNC-drejning og -fræsning, specialmaskiner og metalemner produceret i Rumænien og leveret {to} på {days} arbejdsdage. Prototyper og serier – bed om et tilbud.',
 h1='CNC-bearbejdning og specialmaskiner <span class="gt">til virksomheder {in}</span>',
 badge='Produceret i Rumænien · levering {to}',
 lead='DajbocTechDon S.R.L. fremstiller præcisionsemner i metal på CNC-maskiner og konstruerer og bygger specialmaskiner på eget værksted i Satu Mare, Rumænien. Vi leverer prototyper, enkeltemner, reservedele samt små og mellemstore serier til virksomheder {in} – fra jeres tegning til levering.',
 cta_quote='Bed om tilbud', cta_services='Vores ydelser',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km i luftlinje',
 f_transit='Vejtransport (vejledende)', f_transit_v='{days} arbejdsdage',
 f_customs='Told', f_quote='Tilbud', f_quote_v='i EUR · på engelsk',
 customs_short=dict(eu='Ingen – EU’s indre marked'),
 customs_long=dict(eu='{nom} er ligesom Rumænien medlem af Den Europæiske Union: ingen toldformaliteter og ingen told. Leverancer til virksomheder med gyldigt EU-momsnummer faktureres som leverance inden for EU uden rumænsk moms (omvendt betalingspligt).'),
 svc_tag='Det gør vi', svc_title='CNC-bearbejdning og konstruktion til virksomheder {in}',
 svc_intro='Én leverandør til hele kæden – fra de første krav til et færdigt, testet produkt leveret {to}.',
 svc=[('Krav og engineering', 'Vi afklarer mål, specifikationer, tolerancer, materialer og antal sammen med jer, før konstruktionen starter.'),
      ('Maskinkonstruktion', 'Konstruktion af emner, fiksturer og specialmaskiner til bilindustri, industri, landbrug og energi.'),
      ('Simulering', 'Kontrol af bæreevne, overensstemmelse og funktion før produktionen.'),
      ('CNC-drejning og -fræsning', 'Præcisionsbearbejdning af metalemner på eget værksted – fra prototype til serie.'),
      ('Montage', 'Montage af bearbejdede og indkøbte dele til komplette, funktionsdygtige enheder.'),
      ('Produktionsstyring', 'Processtyring og kvalitetskontrol i alle faser af produktionen.'),
      ('Test', 'Mål- og funktionskontrol, så hvert emne opfylder kravene til sikkerhed og ydeevne.'),
      ('Logistik og levering', 'Emballering, dokumenter og transport helt frem til jeres virksomhed, i hele Europa.')],
 ind_tag='Brancher', ind_title='Brancher vi betjener {in}',
 ind_intro='Industrien {in} er særligt stærk inden for: {sectors}. Til virksomheder i disse brancher fremstiller vi komponenter, reservedele og specialmaskiner:',
 ind=[('Bilindustri', 'Drejede og fræsede præcisionsemner, fiksturer og delmontager til producenter og underleverandører.'),
      ('Industri og maskiner', 'Specialmaskiner, fiksturer, lærer og reservedele til produktionslinjer og vedligehold.'),
      ('Landbrug', 'Komponenter og udstyr til landbrugsmaskiner, bygget til hårde forhold.'),
      ('Energi', 'Dele og enheder til energiproduktion og energiinfrastruktur – sikre og pålidelige.')],
 why_tag='Hvorfor Rumænien', why_title='Hvorfor en CNC-partner i Rumænien?',
 why=['Rumænien er EU-medlem – europæiske standarder, europæisk aftaleret og enkel handel.',
      'Konkurrencedygtige produktionsomkostninger og moderne CNC-maskiner.',
      'Alt på ét værksted: konstruktion, simulering, bearbejdning, montage og test.',
      'Prototyper, enkeltemner, små og mellemstore serier – ingen høje minimumsantal.',
      'Direkte kontakt med de ingeniører, der fremstiller jeres emner.'],
 img_alt='CNC-bearbejdning på DajbocTechDons værksted i Satu Mare, Rumænien',
 how_tag='Sådan foregår det', how_title='Fra tegning til levering i fire trin',
 how=[('Send forespørgsel', 'Tegning eller 3D-model (PDF, STEP, IGES, DXF), materiale, antal og ønsket dato.'),
      ('Få et tilbud', 'Vi vurderer gennemførligheden og oplyser pris og leveringstid.'),
      ('Produktion', 'Bearbejdning, montage og test på vores værksted med kvalitetskontrol i hvert trin.'),
      ('Levering', 'Emballeret, dokumenteret og sendt til jeres adresse.')],
 log_tag='Logistik', log_title='Levering {to}: transittider, told og moms',
 log_p1='Vores værksted ligger i Turț i amtet Satu Mare i det nordvestlige Rumænien – ca. {km} km i luftlinje fra {city}. Emnerne sendes med lastbil (stykgods eller hel bil) eller med ekspreskurér ved små, hastende dele; normal transittid {to} er {days} arbejdsdage. Vi leverer i hele landet, også til industriområder som {hubs}.',
 log_p3='Leveringsbetingelserne (f.eks. EXW, FCA eller DAP jeres fabrik) aftales i tilbuddet. Emnerne rengøres, korrosionsbeskyttes efter behov og pakkes til transport; hver forsendelse følges af leveringsdokumenter og på anmodning af kontrolrapporter.',
 faq_title='Spørgsmål fra kunder {in}',
 faq=[('Leverer I CNC-emner {to}?', 'Ja. Vi sender drejede og fræsede emner, delmontager og komplette maskiner {to} med lastbil eller kurér. Normal transittid fra Satu Mare er {days} arbejdsdage afhængigt af destination og transportform.'),
      ('Hvad skal I bruge til et tilbud?', 'En teknisk tegning eller 3D-model (PDF, STEP, IGES eller DXF), materiale, antal og ønsket leveringsdato. Har I kun en prøve eller en idé, tager vi udgangspunkt i kravene og konstruerer emnet for jer.'),
      ('Laver I prototyper og enkeltemner?', 'Ja. Vi fremstiller prototyper, enkeltemner og reservedele samt små og mellemstore serier; hvert emne bearbejdes og kontrolleres på vores eget værksted.'),
      ('Hvilket sprog kan vi kommunikere på?', 'Vores team arbejder på engelsk og rumænsk. Tilbud, tegninger og leveringsdokumenter er på engelsk; jeres forespørgsel må gerne sendes på dansk.')],
 faq_customs_q='Er der told eller moms ved leverancer {to}?',
 con_tag='Kontakt', con_title='Bed om et tilbud',
 con_p='Send os jeres tegning og krav – vi vender tilbage med pris og leveringstid {to}.',
 l_phone='Telefon', l_addr='Adresse', romania='Rumænien',
 f_name='Navn', f_email='E-mail', f_company='Virksomhed (valgfrit)', f_msg='Besked – beskriv emnet eller projektet',
 f_send='Send forespørgsel', f_sending='Sender…', f_sent='✓ Sendt – vi vender snart tilbage.', f_error='✗ Fejl – prøv igen', f_missing='Udfyld navn, e-mail og besked.',
 more_tag='Europa', more_title='Vi leverer i hele Europa', more_all='Alle lande',
 bc_home='Forside', bc_eu='Europa', bc_page='{N}',
 nav_home='Forside', nav_services='Ydelser', nav_contact='Kontakt', skip='Til indholdet',
 foot='CNC-bearbejdning og specialmaskiner, Satu Mare, Rumænien',
)

# --------------------------------------------------------------- NORSK (bokmål)
L['nb'] = dict(
 code='nb', kw='CNC-maskinering', svc_name='CNC-maskinering og spesialmaskiner for bedrifter {in}',
 title='CNC-maskinering for bedrifter {in} | Produsent i Romania – DajbocTechDon',
 desc='CNC-dreiing og -fresing, spesialmaskiner og metalldeler produsert i Romania og levert {to} på {days} arbeidsdager. Prototyper og serier – be om tilbud.',
 h1='CNC-maskinering og spesialmaskiner <span class="gt">for bedrifter {in}</span>',
 badge='Produsert i Romania · levering {to}',
 lead='DajbocTechDon S.R.L. produserer presisjonsdeler i metall i CNC-maskiner og konstruerer og bygger spesialmaskiner i eget verksted i Satu Mare, Romania. Vi leverer prototyper, enkeltdeler, reservedeler samt små og mellomstore serier til bedrifter {in} – fra deres tegning til levering.',
 cta_quote='Be om tilbud', cta_services='Våre tjenester',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km i luftlinje',
 f_transit='Veitransport (veiledende)', f_transit_v='{days} arbeidsdager',
 f_customs='Toll', f_quote='Tilbud', f_quote_v='i EUR · på engelsk',
 customs_short=dict(eea='EØS · eksportdokumenter fra oss'),
 customs_long=dict(eea='Norge er med i EØS, men ikke i EUs tollunion. Vi utarbeider eksportdeklarasjonen og opprinnelseserklæringen, slik at industrivarer med preferanseopprinnelse i EU som regel kan importeres tollfritt; merverdiavgift ved innførsel betales i Norge ved fortolling.'),
 svc_tag='Dette gjør vi', svc_title='CNC-maskinering og konstruksjon for bedrifter {in}',
 svc_intro='Én leverandør for hele kjeden – fra de første kravene til et ferdig, testet produkt levert {to}.',
 svc=[('Krav og engineering', 'Vi avklarer mål, spesifikasjoner, toleranser, materialer og antall sammen med dere før konstruksjonen starter.'),
      ('Maskinkonstruksjon', 'Konstruksjon av deler, fiksturer og spesialmaskiner for bilindustri, industri, landbruk og energi.'),
      ('Simulering', 'Kontroll av bæreevne, samsvar og funksjon før produksjonen.'),
      ('CNC-dreiing og -fresing', 'Presisjonsbearbeiding av metalldeler i eget verksted – fra prototype til serie.'),
      ('Montering', 'Montering av bearbeidede og innkjøpte deler til komplette, fungerende enheter.'),
      ('Produksjonsstyring', 'Prosesstyring og kvalitetskontroll i alle faser av produksjonen.'),
      ('Testing', 'Mål- og funksjonskontroll slik at hver del oppfyller kravene til sikkerhet og ytelse.'),
      ('Logistikk og levering', 'Pakking, dokumenter og transport helt frem til anlegget deres, i hele Europa.')],
 ind_tag='Bransjer', ind_title='Bransjer vi betjener {in}',
 ind_intro='Industrien {in} er særlig sterk innen: {sectors}. For bedrifter i disse bransjene produserer vi komponenter, reservedeler og spesialmaskiner:',
 ind=[('Bilindustri', 'Dreide og freste presisjonsdeler, fiksturer og delmonteringer for produsenter og underleverandører.'),
      ('Industri og maskiner', 'Spesialmaskiner, fiksturer, måleverktøy og reservedeler for produksjonslinjer og vedlikehold.'),
      ('Landbruk', 'Komponenter og utstyr til landbruksmaskiner, bygget for tøffe forhold.'),
      ('Energi', 'Deler og enheter for energiproduksjon og energiinfrastruktur – sikre og pålitelige.')],
 why_tag='Hvorfor Romania', why_title='Hvorfor en CNC-partner i Romania?',
 why=['Romania er EU-medlem – europeiske standarder og enkel handel med hele EØS.',
      'Konkurransedyktige produksjonskostnader og moderne CNC-maskiner.',
      'Alt i ett verksted: konstruksjon, simulering, bearbeiding, montering og testing.',
      'Prototyper, enkeltdeler, små og mellomstore serier – ingen høye minimumskvanta.',
      'Direkte kontakt med ingeniørene som lager delene deres.'],
 img_alt='CNC-maskinering i DajbocTechDons verksted i Satu Mare, Romania',
 how_tag='Slik fungerer det', how_title='Fra tegning til levering i fire trinn',
 how=[('Send forespørsel', 'Tegning eller 3D-modell (PDF, STEP, IGES, DXF), materiale, antall og ønsket dato.'),
      ('Få tilbud', 'Vi vurderer gjennomførbarheten og oppgir pris og leveringstid.'),
      ('Produksjon', 'Bearbeiding, montering og testing i vårt verksted med kvalitetskontroll i hvert trinn.'),
      ('Levering', 'Pakket, dokumentert og sendt til deres adresse.')],
 log_tag='Logistikk', log_title='Levering {to}: transittid, toll og mva.',
 log_p1='Verkstedet vårt ligger i Turț i fylket Satu Mare nordvest i Romania – om lag {km} km i luftlinje fra {city}. Delene sendes med lastebil (stykkgods eller full bil) eller med ekspressbud for små hastedeler; normal transittid {to} er {days} arbeidsdager inkludert fortolling. Vi leverer i hele landet, også til industriregioner som {hubs}.',
 log_p3='Leveringsbetingelsene (f.eks. EXW, FCA eller DAP deres fabrikk) avtales i tilbudet. Delene rengjøres, korrosjonsbeskyttes ved behov og pakkes for transport; hver sending følges av leveringsdokumenter og på forespørsel av kontrollrapporter.',
 faq_title='Spørsmål fra kunder {in}',
 faq=[('Leverer dere CNC-deler {to}?', 'Ja. Vi sender dreide og freste deler, delmonteringer og komplette maskiner {to} med lastebil eller bud. Normal transittid fra Satu Mare er {days} arbeidsdager, avhengig av destinasjon og fortolling.'),
      ('Hva trenger dere for å gi tilbud?', 'En teknisk tegning eller 3D-modell (PDF, STEP, IGES eller DXF), materiale, antall og ønsket leveringsdato. Har dere bare en prøve eller en idé, tar vi utgangspunkt i kravene og konstruerer delen for dere.'),
      ('Lager dere prototyper og enkeltdeler?', 'Ja. Vi produserer prototyper, enkeltdeler og reservedeler samt små og mellomstore serier; hver del bearbeides og kontrolleres i vårt eget verksted.'),
      ('Hvilket språk kan vi kommunisere på?', 'Teamet vårt arbeider på engelsk og rumensk. Tilbud, tegninger og leveringsdokumenter er på engelsk; forespørselen kan gjerne sendes på norsk.')],
 faq_customs_q='Blir det toll eller merverdiavgift ved leveranser {to}?',
 con_tag='Kontakt', con_title='Be om tilbud',
 con_p='Send oss tegning og krav – vi kommer tilbake med pris og leveringstid {to}.',
 l_phone='Telefon', l_addr='Adresse', romania='Romania',
 f_name='Navn', f_email='E-post', f_company='Bedrift (valgfritt)', f_msg='Melding – beskriv delen eller prosjektet',
 f_send='Send forespørsel', f_sending='Sender…', f_sent='✓ Sendt – vi tar kontakt snart.', f_error='✗ Feil – prøv igjen', f_missing='Fyll inn navn, e-post og melding.',
 more_tag='Europa', more_title='Vi leverer i hele Europa', more_all='Alle land',
 bc_home='Hjem', bc_eu='Europa', bc_page='{N}',
 nav_home='Hjem', nav_services='Tjenester', nav_contact='Kontakt', skip='Til innholdet',
 foot='CNC-maskinering og spesialmaskiner, Satu Mare, Romania',
)

# --------------------------------------------------------------- SUOMI
L['fi'] = dict(
 code='fi', kw='CNC-koneistus', svc_name='CNC-koneistus ja erikoiskoneet yrityksille {in}',
 title='CNC-koneistus yrityksille {in} | Valmistaja Romaniasta – DajbocTechDon',
 desc='CNC-sorvaus ja -jyrsintä, erikoiskoneet ja metalliosat Romaniasta, toimitus {to} {days} arkipäivässä. Prototyypit ja sarjat – pyydä tarjous.',
 h1='CNC-koneistus ja erikoiskoneet <span class="gt">yrityksille {in}</span>',
 badge='Valmistettu Romaniassa · toimitus {to}',
 lead='DajbocTechDon S.R.L. valmistaa tarkkuusmetalliosia CNC-koneilla sekä suunnittelee ja rakentaa erikoiskoneita omassa konepajassaan Satu Maressa, Romaniassa. Toimitamme yrityksille {in} prototyyppejä, yksittäisiä osia, varaosia sekä pieniä ja keskisuuria sarjoja – piirustuksestanne toimitukseen asti.',
 cta_quote='Pyydä tarjous', cta_services='Palvelumme',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km linnuntietä',
 f_transit='Maantiekuljetus (suuntaa-antava)', f_transit_v='{days} arkipäivää',
 f_customs='Tulli', f_quote='Tarjoukset', f_quote_v='euroissa · englanniksi',
 customs_short=dict(eu='Ei tullia – EU:n sisämarkkinat'),
 customs_long=dict(eu='{nom} on Romanian tavoin Euroopan unionin jäsen: ei tullimuodollisuuksia eikä tulleja. Toimitukset yrityksille, joilla on voimassa oleva EU-arvonlisäverotunniste, laskutetaan yhteisömyyntinä ilman Romanian arvonlisäveroa (käännetty verovelvollisuus).'),
 svc_tag='Mitä teemme', svc_title='CNC-koneistus ja suunnittelu yrityksille {in}',
 svc_intro='Yksi toimittaja koko ketjulle – ensimmäisistä vaatimuksista valmiiseen, testattuun tuotteeseen, joka toimitetaan {to}.',
 svc=[('Vaatimukset ja suunnittelu', 'Määritämme kanssanne tavoitteet, spesifikaatiot, toleranssit, materiaalit ja määrät ennen suunnittelua.'),
      ('Konesuunnittelu', 'Osien, kiinnittimien ja erikoiskoneiden suunnittelu autoteollisuuteen, teollisuuteen, maatalouteen ja energia-alalle.'),
      ('Simulointi', 'Kantavuuden, vaatimustenmukaisuuden ja toiminnan tarkistus ennen valmistusta.'),
      ('CNC-sorvaus ja -jyrsintä', 'Metalliosien tarkkuuskoneistus omassa konepajassa – prototyypistä sarjaan.'),
      ('Kokoonpano', 'Koneistettujen ja ostettujen osien kokoaminen valmiiksi, toimiviksi kokonaisuuksiksi.'),
      ('Tuotannonohjaus', 'Prosessinohjaus ja laadunvalvonta tuotannon jokaisessa vaiheessa.'),
      ('Testaus', 'Mitta- ja toimintatarkastus, jotta jokainen osa täyttää turvallisuus- ja suorituskykyvaatimukset.'),
      ('Logistiikka ja toimitus', 'Pakkaus, asiakirjat ja kuljetus tehtaallenne kaikkialla Euroopassa.')],
 ind_tag='Toimialat', ind_title='Toimialat, joita palvelemme',
 ind_intro='Teollisuus {in} on erityisen vahvaa seuraavilla aloilla: {sectors}. Näiden alojen yrityksille valmistamme komponentteja, varaosia ja erikoiskoneita:',
 ind=[('Autoteollisuus', 'Sorvatut ja jyrsityt tarkkuusosat, kiinnittimet ja osakokoonpanot valmistajille ja alihankkijoille.'),
      ('Teollisuus ja koneet', 'Erikoiskoneet, kiinnittimet, tulkit ja varaosat tuotantolinjoille ja kunnossapitoon.'),
      ('Maatalous', 'Maatalouskoneiden komponentit ja varusteet vaativiin olosuhteisiin.'),
      ('Energia', 'Osat ja kokonaisuudet energiantuotantoon ja energiainfrastruktuuriin – turvallisesti ja luotettavasti.')],
 why_tag='Miksi Romania', why_title='Miksi CNC-kumppani Romaniasta?',
 why=['Romania on EU:n jäsen – eurooppalaiset standardit, EU:n sopimusoikeus ja helppo kauppa.',
      'Kilpailukykyiset valmistuskustannukset ja nykyaikaiset CNC-koneet.',
      'Kaikki yhdessä konepajassa: suunnittelu, simulointi, koneistus, kokoonpano ja testaus.',
      'Prototyypit, yksittäiset osat, pienet ja keskisuuret sarjat – ei suuria minimimääriä.',
      'Suora yhteys insinööreihin, jotka valmistavat osanne.'],
 img_alt='CNC-koneistusta DajbocTechDonin konepajassa Satu Maressa, Romaniassa',
 how_tag='Näin toimimme', how_title='Piirustuksesta toimitukseen neljässä vaiheessa',
 how=[('Lähetä tarjouspyyntö', 'Piirustus tai 3D-malli (PDF, STEP, IGES, DXF), materiaali, määrä ja toivottu päivämäärä.'),
      ('Saat tarjouksen', 'Tarkistamme toteutettavuuden ja ilmoitamme hinnan ja toimitusajan.'),
      ('Valmistus', 'Koneistus, kokoonpano ja testaus konepajassamme, laadunvalvonta joka vaiheessa.'),
      ('Toimitus', 'Pakattuna ja asiakirjoineen osoitteeseenne.')],
 log_tag='Logistiikka', log_title='Toimitus {to}: kuljetusajat, tulli ja arvonlisävero',
 log_p1='Konepajamme sijaitsee Turțissa Satu Maren läänissä Luoteis-Romaniassa – noin {km} km linnuntietä {city_log}. Osat kulkevat maanteitse (kappaletavarana tai kokokuormana) ja pienet kiireelliset osat pikakuriirilla; tavallinen kuljetusaika {to} on {days} arkipäivää. Toimitamme koko maahan, myös teollisuusalueille kuten {hubs}.',
 log_p3='Toimitusehdot (esim. EXW, FCA tai DAP tehtaallenne) sovitaan tarjouksessa. Osat puhdistetaan, suojataan tarvittaessa korroosiolta ja pakataan kuljetusta varten; jokaisen lähetyksen mukana ovat toimitusasiakirjat ja pyynnöstä tarkastusraportit.',
 faq_title='Asiakkaidemme kysymyksiä',
 faq=[('Toimitatteko CNC-osia {to}?', 'Kyllä. Lähetämme sorvattuja ja jyrsittyjä osia, osakokoonpanoja ja kokonaisia koneita {to} rekalla tai kuriirilla. Tavallinen kuljetusaika Satu Maresta on {days} arkipäivää kohteesta ja kuljetustavasta riippuen.'),
      ('Mitä tarvitsette tarjousta varten?', 'Teknisen piirustuksen tai 3D-mallin (PDF, STEP, IGES tai DXF), materiaalin, määrän ja toivotun toimituspäivän. Jos teillä on vain mallikappale tai idea, lähdemme liikkeelle vaatimuksista ja suunnittelemme osan puolestanne.'),
      ('Valmistatteko prototyyppejä ja yksittäisiä osia?', 'Kyllä. Valmistamme prototyyppejä, yksittäisiä osia ja varaosia sekä pieniä ja keskisuuria sarjoja; jokainen osa koneistetaan ja tarkastetaan omassa konepajassamme.'),
      ('Millä kielellä voimme asioida?', 'Tiimimme työskentelee englanniksi ja romaniaksi. Tarjoukset, piirustukset ja toimitusasiakirjat ovat englanniksi; tarjouspyynnön voi lähettää myös suomeksi.')],
 faq_customs_q='Peritäänkö toimituksista {to} tullia tai arvonlisäveroa?',
 con_tag='Yhteystiedot', con_title='Pyydä tarjous',
 con_p='Lähetä meille piirustus ja vaatimukset – vastaamme hinnalla ja toimitusajalla.',
 l_phone='Puhelin', l_addr='Osoite', romania='Romania',
 f_name='Nimi', f_email='Sähköposti', f_company='Yritys (valinnainen)', f_msg='Viesti – kuvaile osa tai projekti',
 f_send='Lähetä tarjouspyyntö', f_sending='Lähetetään…', f_sent='✓ Lähetetty – palaamme asiaan pian.', f_error='✗ Virhe – yritä uudelleen', f_missing='Täytä nimi, sähköposti ja viesti.',
 more_tag='Eurooppa', more_title='Toimitamme koko Eurooppaan', more_all='Kaikki maat',
 bc_home='Etusivu', bc_eu='Eurooppa', bc_page='{N}',
 nav_home='Etusivu', nav_services='Palvelut', nav_contact='Yhteystiedot', skip='Siirry sisältöön',
 foot='CNC-koneistus ja erikoiskoneet, Satu Mare, Romania',
)

# --------------------------------------------------------------- EESTI
L['et'] = dict(
 code='et', kw='CNC-töötlus', svc_name='CNC-töötlus ja eriotstarbelised masinad ettevõtetele {in}',
 title='CNC-töötlus ettevõtetele {in} | Tootja Rumeeniast – DajbocTechDon',
 desc='CNC-treimine ja -freesimine, eriotstarbelised masinad ja metalldetailid Rumeeniast, tarne {to} {days} tööpäevaga. Prototüübid ja seeriad – küsige pakkumist.',
 h1='CNC-töötlus ja eriotstarbelised masinad <span class="gt">ettevõtetele {in}</span>',
 badge='Toodetud Rumeenias · tarne {to}',
 lead='DajbocTechDon S.R.L. valmistab CNC-pinkidel täppismetalldetaile ning projekteerib ja ehitab eriotstarbelisi masinaid oma töökojas Satu Mares Rumeenias. Tarnime ettevõtetele {in} prototüüpe, üksikdetaile, varuosi ning väikese ja keskmise suurusega seeriaid – teie joonisest kuni tarneni.',
 cta_quote='Küsi pakkumist', cta_services='Meie teenused',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km linnulennult',
 f_transit='Maanteetransport (ligikaudu)', f_transit_v='{days} tööpäeva',
 f_customs='Toll', f_quote='Pakkumised', f_quote_v='eurodes · inglise keeles',
 customs_short=dict(eu='Puudub – ELi siseturg'),
 customs_long=dict(eu='{nom} on nagu Rumeeniagi Euroopa Liidu liige: tolliformaalsusi ega tollimakse ei ole. Tarned kehtiva ELi käibemaksukohustuslase numbriga ettevõtetele arveldame ühendusesisese kättetoimetamisena ilma Rumeenia käibemaksuta (pöördmaksustamine).'),
 svc_tag='Mida me teeme', svc_title='CNC-töötlus ja inseneriteenused ettevõtetele {in}',
 svc_intro='Üks tarnija kogu ahelale – esimestest nõuetest valmis ja testitud tooteni, mis tarnitakse {to}.',
 svc=[('Nõuded ja inseneritöö', 'Enne projekteerimist täpsustame koos teiega eesmärgid, spetsifikatsioonid, tolerantsid, materjalid ja kogused.'),
      ('Mehaaniline projekteerimine', 'Detailide, rakiste ja eriotstarbeliste masinate projekteerimine autotööstusele, tööstusele, põllumajandusele ja energeetikale.'),
      ('Simulatsioon', 'Kandevõime, vastavuse ja toimimise kontroll enne tootmist.'),
      ('CNC-treimine ja -freesimine', 'Metalldetailide täppistöötlus oma töökojas – prototüübist seeriani.'),
      ('Koostamine', 'Töödeldud ja ostetud detailide koostamine terviklikeks, töötavateks sõlmedeks.'),
      ('Tootmise juhtimine', 'Protsessi juhtimine ja kvaliteedikontroll tootmise igas etapis.'),
      ('Testimine', 'Mõõtme- ja funktsionaalne kontroll, et iga detail vastaks ohutus- ja jõudlusnõuetele.'),
      ('Logistika ja tarne', 'Pakkimine, dokumendid ja transport kuni teie tehaseni üle kogu Euroopa.')],
 ind_tag='Valdkonnad', ind_title='Valdkonnad, mida teenindame',
 ind_intro='Tööstus {in} on eriti tugev järgmistes valdkondades: {sectors}. Nende valdkondade ettevõtetele valmistame komponente, varuosi ja eriotstarbelisi masinaid:',
 ind=[('Autotööstus', 'Treitud ja freesitud täppisdetailid, rakised ja alamkoostud tootjatele ja allhankijatele.'),
      ('Tööstus ja masinaehitus', 'Eriotstarbelised masinad, rakised, kaliibrid ja varuosad tootmisliinidele ja hoolduseks.'),
      ('Põllumajandus', 'Põllumajandusmasinate komponendid ja seadmed rasketeks tingimusteks.'),
      ('Energeetika', 'Detailid ja sõlmed energiatootmisele ja energiataristule – ohutud ja töökindlad.')],
 why_tag='Miks Rumeenia', why_title='Miks CNC-partner Rumeeniast?',
 why=['Rumeenia on ELi liige – Euroopa standardid, ELi lepinguõigus ja lihtne kaubandus.',
      'Konkurentsivõimelised tootmiskulud ja kaasaegsed CNC-pingid.',
      'Kõik ühes töökojas: projekteerimine, simulatsioon, töötlemine, koostamine ja testimine.',
      'Prototüübid, üksikdetailid, väikesed ja keskmised seeriad – ilma suurte miinimumkogusteta.',
      'Otsekontakt inseneridega, kes teie detaile valmistavad.'],
 img_alt='CNC-töötlus DajbocTechDoni töökojas Satu Mares, Rumeenias',
 how_tag='Kuidas me töötame', how_title='Joonisest tarneni nelja sammuga',
 how=[('Saatke päring', 'Joonis või 3D-mudel (PDF, STEP, IGES, DXF), materjal, kogus ja soovitud tähtaeg.'),
      ('Saage pakkumine', 'Kontrollime teostatavust ning teatame hinna ja tarneaja.'),
      ('Tootmine', 'Töötlemine, koostamine ja testimine meie töökojas, kvaliteedikontroll igas etapis.'),
      ('Tarne', 'Pakitud, dokumenteeritud ja saadetud teie aadressile.')],
 log_tag='Logistika', log_title='Tarne {to}: veoajad, toll ja käibemaks',
 log_p1='Meie töökoda asub Turțis, Satu Mare maakonnas Loode-Rumeenias – linnulennult umbes {km} km kaugusel {city_log}. Detailid saadetakse maanteed pidi (koondveosena või täiskoormana), väikesed kiireloomulised detailid kullerteenusega; tavaline veoaeg {to} on {days} tööpäeva. Tarnime kogu riiki, sealhulgas tööstuspiirkondadesse nagu {hubs}.',
 log_p3='Tarnetingimused (nt EXW, FCA või DAP teie tehas) lepitakse kokku pakkumises. Detailid puhastatakse, vajadusel kaitstakse korrosiooni eest ja pakitakse transpordiks; iga saadetisega on kaasas saatedokumendid ja soovi korral kontrolliaruanded.',
 faq_title='Klientide küsimused',
 faq=[('Kas tarnite CNC-detaile {to}?', 'Jah. Saadame treitud ja freesitud detaile, alamkoostusid ja terveid masinaid {to} veoauto või kulleriga. Tavaline veoaeg Satu Marest on {days} tööpäeva, sõltuvalt sihtkohast ja veoviisist.'),
      ('Mida on pakkumise jaoks vaja?', 'Tehnilist joonist või 3D-mudelit (PDF, STEP, IGES või DXF), materjali, kogust ja soovitud tarnekuupäeva. Kui teil on ainult näidis või idee, lähtume nõuetest ja projekteerime detaili teie eest.'),
      ('Kas valmistate prototüüpe ja üksikdetaile?', 'Jah. Valmistame prototüüpe, üksikdetaile ja varuosi ning väikeseid ja keskmisi seeriaid; iga detail töödeldakse ja kontrollitakse meie oma töökojas.'),
      ('Mis keeles saame suhelda?', 'Meie meeskond töötab inglise ja rumeenia keeles. Pakkumised, joonised ja saatedokumendid on inglise keeles; päringu võite saata ka eesti keeles.')],
 faq_customs_q='Kas tarnetel {to} tuleb maksta tolli või käibemaksu?',
 con_tag='Kontakt', con_title='Küsi pakkumist',
 con_p='Saatke meile joonis ja nõuded – vastame hinna ja tarneajaga.',
 l_phone='Telefon', l_addr='Aadress', romania='Rumeenia',
 f_name='Nimi', f_email='E-post', f_company='Ettevõte (valikuline)', f_msg='Sõnum – kirjeldage detaili või projekti',
 f_send='Saada päring', f_sending='Saatmine…', f_sent='✓ Saadetud – võtame peagi ühendust.', f_error='✗ Viga – proovige uuesti', f_missing='Täitke nimi, e-post ja sõnum.',
 more_tag='Euroopa', more_title='Tarnime üle kogu Euroopa', more_all='Kõik riigid',
 bc_home='Avaleht', bc_eu='Euroopa', bc_page='{N}',
 nav_home='Avaleht', nav_services='Teenused', nav_contact='Kontakt', skip='Sisu juurde',
 foot='CNC-töötlus ja eriotstarbelised masinad, Satu Mare, Rumeenia',
)

# --------------------------------------------------------------- LATVIEŠU
L['lv'] = dict(
 code='lv', kw='CNC apstrāde', svc_name='CNC apstrāde un speciālās iekārtas uzņēmumiem {in}',
 title='CNC apstrāde uzņēmumiem {in} | Ražotājs no Rumānijas – DajbocTechDon',
 desc='CNC virpošana un frēzēšana, speciālās iekārtas un metāla detaļas no Rumānijas ar piegādi {to} {days} darba dienās. Prototipi un sērijas – pieprasiet piedāvājumu.',
 h1='CNC apstrāde un speciālās iekārtas <span class="gt">uzņēmumiem {in}</span>',
 badge='Ražots Rumānijā · piegāde {to}',
 lead='DajbocTechDon S.R.L. izgatavo precīzas metāla detaļas ar CNC darbgaldiem, kā arī projektē un būvē speciālās iekārtas savā darbnīcā Satu Marē, Rumānijā. Uzņēmumiem {in} piegādājam prototipus, atsevišķas detaļas, rezerves daļas, kā arī mazas un vidējas sērijas – no jūsu rasējuma līdz piegādei.',
 cta_quote='Pieprasīt piedāvājumu', cta_services='Mūsu pakalpojumi',
 f_dist='Satu Mare – {city}', f_dist_v='≈ {km} km taisnā līnijā',
 f_transit='Autopārvadājums (orientējoši)', f_transit_v='{days} darba dienas',
 f_customs='Muita', f_quote='Piedāvājumi', f_quote_v='EUR · angļu valodā',
 customs_short=dict(eu='Nav – ES vienotais tirgus'),
 customs_long=dict(eu='{nom}, tāpat kā Rumānija, ir Eiropas Savienības dalībvalsts: nav muitas formalitāšu un muitas nodokļu. Piegādes uzņēmumiem ar derīgu ES PVN reģistrācijas numuru mēs rēķinām kā preču piegādi Kopienas iekšienē bez Rumānijas PVN (apgrieztā maksāšana).'),
 svc_tag='Ko mēs darām', svc_title='CNC apstrāde un inženierpakalpojumi uzņēmumiem {in}',
 svc_intro='Viens piegādātājs visai ķēdei – no pirmajām prasībām līdz gatavam, pārbaudītam izstrādājumam ar piegādi {to}.',
 svc=[('Prasības un inženierija', 'Pirms projektēšanas kopā ar jums precizējam mērķus, specifikācijas, pielaides, materiālus un daudzumus.'),
      ('Mehāniskā projektēšana', 'Detaļu, ierīču un speciālo iekārtu projektēšana autobūvei, rūpniecībai, lauksaimniecībai un enerģētikai.'),
      ('Simulācija', 'Nestspējas, atbilstības un darbības pārbaude pirms ražošanas.'),
      ('CNC virpošana un frēzēšana', 'Metāla detaļu precīza CNC apstrāde mūsu darbnīcā – no prototipa līdz sērijai.'),
      ('Montāža', 'Apstrādāto un iepirkto detaļu montāža pilnīgos, funkcionējošos mezglos.'),
      ('Ražošanas vadība', 'Procesa vadība un kvalitātes kontrole katrā ražošanas posmā.'),
      ('Testēšana', 'Izmēru un funkcionālā pārbaude, lai katra detaļa atbilstu drošības un veiktspējas prasībām.'),
      ('Loģistika un piegāde', 'Iepakošana, dokumenti un transports līdz jūsu uzņēmumam visā Eiropā.')],
 ind_tag='Nozares', ind_title='Nozares, kuras apkalpojam',
 ind_intro='Rūpniecība {in} ir īpaši spēcīga šādās jomās: {sectors}. Šo nozaru uzņēmumiem izgatavojam komponentus, rezerves daļas un speciālās iekārtas:',
 ind=[('Autobūve', 'Precīzas virpotas un frēzētas detaļas, ierīces un mezgli ražotājiem un piegādātājiem.'),
      ('Rūpniecība un mašīnbūve', 'Speciālās iekārtas, ierīces, kalibri un rezerves daļas ražošanas līnijām un apkopei.'),
      ('Lauksaimniecība', 'Lauksaimniecības tehnikas komponenti un aprīkojums smagiem apstākļiem.'),
      ('Enerģētika', 'Detaļas un mezgli enerģijas ražošanai un enerģētikas infrastruktūrai – droši un uzticami.')],
 why_tag='Kāpēc Rumānija', why_title='Kāpēc CNC partneris Rumānijā?',
 why=['Rumānija ir ES dalībvalsts – Eiropas standarti, ES līgumtiesības un vienkārša tirdzniecība.',
      'Konkurētspējīgas ražošanas izmaksas un moderni CNC darbgaldi.',
      'Viss vienā darbnīcā: projektēšana, simulācija, apstrāde, montāža un testēšana.',
      'Prototipi, atsevišķas detaļas, mazas un vidējas sērijas – bez lieliem minimālajiem daudzumiem.',
      'Tiešs kontakts ar inženieriem, kuri izgatavo jūsu detaļas.'],
 img_alt='CNC apstrāde DajbocTechDon darbnīcā Satu Marē, Rumānijā',
 how_tag='Kā mēs strādājam', how_title='No rasējuma līdz piegādei četros soļos',
 how=[('Nosūtiet pieprasījumu', 'Rasējums vai 3D modelis (PDF, STEP, IGES, DXF), materiāls, daudzums un vēlamais termiņš.'),
      ('Saņemiet piedāvājumu', 'Pārbaudām izpildāmību un paziņojam cenu un termiņu.'),
      ('Ražošana', 'Apstrāde, montāža un testēšana mūsu darbnīcā ar kvalitātes kontroli katrā solī.'),
      ('Piegāde', 'Iepakots, dokumentēts un nosūtīts uz jūsu adresi.')],
 log_tag='Loģistika', log_title='Piegāde {to}: termiņi, muita un PVN',
 log_p1='Mūsu darbnīca atrodas Turcā (Turț), Satu Mares apriņķī, Rumānijas ziemeļrietumos – aptuveni {km} km taisnā līnijā no {city_log}. Detaļas sūtām ar autotransportu (grupāžas kravas vai pilna mašīna), bet mazas steidzamas detaļas – ar ekspreskurjeru; parastais pārvadājuma laiks {to} ir {days} darba dienas. Piegādājam visā valstī, tostarp tādos rūpniecības centros kā {hubs}.',
 log_p3='Piegādes nosacījumus (piemēram, EXW, FCA vai DAP jūsu rūpnīca) nosakām piedāvājumā. Detaļas tiek notīrītas, vajadzības gadījumā aizsargātas pret koroziju un iepakotas transportēšanai; katram sūtījumam pievienojam pavaddokumentus un pēc pieprasījuma – kontroles protokolus.',
 faq_title='Klientu jautājumi',
 faq=[('Vai piegādājat CNC detaļas {to}?', 'Jā. Virpotas un frēzētas detaļas, mezglus un pilnas iekārtas sūtām {to} ar kravas auto vai kurjeru. Parastais pārvadājuma laiks no Satu Mares ir {days} darba dienas atkarībā no galamērķa un transporta veida.'),
      ('Kas nepieciešams piedāvājumam?', 'Tehniskais rasējums vai 3D modelis (PDF, STEP, IGES vai DXF), materiāls, daudzums un vēlamais piegādes datums. Ja jums ir tikai paraugs vai ideja, sākam no prasībām un detaļu izprojektējam jūsu vietā.'),
      ('Vai izgatavojat prototipus un atsevišķas detaļas?', 'Jā. Izgatavojam prototipus, atsevišķas detaļas un rezerves daļas, kā arī mazas un vidējas sērijas; katru detaļu apstrādājam un pārbaudām savā darbnīcā.'),
      ('Kādā valodā varam sazināties?', 'Mūsu komanda strādā angļu un rumāņu valodā. Piedāvājumi, rasējumi un pavaddokumenti ir angļu valodā; pieprasījumu varat sūtīt arī latviski.')],
 faq_customs_q='Vai piegādēm {to} jāmaksā muita vai PVN?',
 con_tag='Kontakti', con_title='Pieprasiet piedāvājumu',
 con_p='Nosūtiet mums rasējumu un prasības – atbildēsim ar cenu un piegādes termiņu.',
 l_phone='Tālrunis', l_addr='Adrese', romania='Rumānija',
 f_name='Vārds', f_email='E-pasts', f_company='Uzņēmums (nav obligāti)', f_msg='Ziņa – aprakstiet detaļu vai projektu',
 f_send='Nosūtīt pieprasījumu', f_sending='Sūta…', f_sent='✓ Nosūtīts – drīzumā sazināsimies.', f_error='✗ Kļūda – mēģiniet vēlreiz', f_missing='Aizpildiet vārdu, e-pastu un ziņu.',
 more_tag='Eiropa', more_title='Piegādājam visā Eiropā', more_all='Visas valstis',
 bc_home='Sākums', bc_eu='Eiropa', bc_page='{N}',
 nav_home='Sākums', nav_services='Pakalpojumi', nav_contact='Kontakti', skip='Uz saturu',
 foot='CNC apstrāde un speciālās iekārtas, Satu Mare, Rumānija',
)

# --------------------------------------------------------------- LIETUVIŲ
L['lt'] = dict(
 code='lt', kw='CNC apdirbimas', svc_name='CNC apdirbimas ir specialios mašinos įmonėms {in}',
 title='CNC apdirbimas įmonėms {in} | Gamintojas iš Rumunijos – DajbocTechDon',
 desc='CNC tekinimas ir frezavimas, specialios mašinos ir metalo detalės iš Rumunijos su pristatymu {to} per {days} darbo dienas. Prototipai ir serijos – užklauskite pasiūlymo.',
 h1='CNC apdirbimas ir specialios mašinos <span class="gt">įmonėms {in}</span>',
 badge='Pagaminta Rumunijoje · pristatymas {to}',
 lead='DajbocTechDon S.R.L. CNC staklėmis gamina tikslias metalo detales, taip pat projektuoja ir stato specialias mašinas savo dirbtuvėse Satu Marėje, Rumunijoje. Įmonėms {in} tiekiame prototipus, vienetines detales, atsargines dalis bei mažas ir vidutines serijas – nuo jūsų brėžinio iki pristatymo.',
 cta_quote='Gauti pasiūlymą', cta_services='Mūsų paslaugos',
 f_dist='Satu Marė – {city}', f_dist_v='≈ {km} km tiesia linija',
 f_transit='Kelių transportas (orientacinis)', f_transit_v='{days} darbo dienos',
 f_customs='Muitas', f_quote='Pasiūlymai', f_quote_v='EUR · anglų kalba',
 customs_short=dict(eu='Nėra – ES bendroji rinka'),
 customs_long=dict(eu='{nom}, kaip ir Rumunija, yra Europos Sąjungos narė: jokių muitinės formalumų ir muitų. Tiekimą įmonėms, turinčioms galiojantį ES PVM mokėtojo kodą, apmokestiname kaip tiekimą Bendrijos viduje be Rumunijos PVM (atvirkštinis apmokestinimas).'),
 svc_tag='Ką darome', svc_title='CNC apdirbimas ir inžinerija įmonėms {in}',
 svc_intro='Vienas tiekėjas visai grandinei – nuo pirmųjų reikalavimų iki pagaminto ir išbandyto gaminio, pristatyto {to}.',
 svc=[('Reikalavimai ir inžinerija', 'Prieš projektuodami kartu su jumis aptariame tikslus, specifikacijas, leistinus nuokrypius, medžiagas ir kiekius.'),
      ('Mechaninis projektavimas', 'Detalių, įtaisų ir specialių mašinų projektavimas automobilių pramonei, pramonei, žemės ūkiui ir energetikai.'),
      ('Modeliavimas', 'Laikomosios galios, atitikties ir veikimo patikra prieš gamybą.'),
      ('CNC tekinimas ir frezavimas', 'Tikslus metalo detalių CNC apdirbimas mūsų dirbtuvėse – nuo prototipo iki serijos.'),
      ('Surinkimas', 'Apdirbtų ir pirktų detalių surinkimas į pilnus, veikiančius mazgus.'),
      ('Gamybos valdymas', 'Proceso valdymas ir kokybės kontrolė kiekviename gamybos etape.'),
      ('Bandymai', 'Matmenų ir funkcinė patikra, kad kiekviena detalė atitiktų saugos ir našumo reikalavimus.'),
      ('Logistika ir pristatymas', 'Pakavimas, dokumentai ir transportas iki jūsų įmonės visoje Europoje.')],
 ind_tag='Sektoriai', ind_title='Sektoriai, kuriuos aptarnaujame',
 ind_intro='Pramonė {in} ypač stipri šiose srityse: {sectors}. Šių sektorių įmonėms gaminame komponentus, atsargines dalis ir specialias mašinas:',
 ind=[('Automobilių pramonė', 'Tikslios tekintos ir frezuotos detalės, įtaisai ir mazgai gamintojams bei tiekėjams.'),
      ('Pramonė ir mašinų gamyba', 'Specialios mašinos, įtaisai, kalibrai ir atsarginės dalys gamybos linijoms ir priežiūrai.'),
      ('Žemės ūkis', 'Žemės ūkio technikos komponentai ir įranga, pritaikyti sunkioms sąlygoms.'),
      ('Energetika', 'Detalės ir mazgai energijos gamybai ir energetikos infrastruktūrai – saugūs ir patikimi.')],
 why_tag='Kodėl Rumunija', why_title='Kodėl CNC partneris Rumunijoje?',
 why=['Rumunija yra ES narė – europiniai standartai, ES sutarčių teisė ir paprasta prekyba.',
      'Konkurencingos gamybos sąnaudos ir modernios CNC staklės.',
      'Viskas vienose dirbtuvėse: projektavimas, modeliavimas, apdirbimas, surinkimas ir bandymai.',
      'Prototipai, vienetinės detalės, mažos ir vidutinės serijos – be didelių minimalių kiekių.',
      'Tiesioginis ryšys su inžinieriais, kurie gamina jūsų detales.'],
 img_alt='CNC apdirbimas DajbocTechDon dirbtuvėse Satu Marėje, Rumunijoje',
 how_tag='Kaip dirbame', how_title='Nuo brėžinio iki pristatymo per keturis žingsnius',
 how=[('Atsiųskite užklausą', 'Brėžinys arba 3D modelis (PDF, STEP, IGES, DXF), medžiaga, kiekis ir pageidaujamas terminas.'),
      ('Gaukite pasiūlymą', 'Įvertiname įgyvendinamumą ir pateikiame kainą bei terminą.'),
      ('Gamyba', 'Apdirbimas, surinkimas ir bandymai mūsų dirbtuvėse, kokybės kontrolė kiekviename žingsnyje.'),
      ('Pristatymas', 'Supakuota, su dokumentais ir išsiųsta jūsų adresu.')],
 log_tag='Logistika', log_title='Pristatymas {to}: terminai, muitas ir PVM',
 log_p1='Mūsų dirbtuvės yra Turce (Turț), Satu Marės apskrityje, šiaurės vakarų Rumunijoje – maždaug {km} km tiesia linija nuo {city_log}. Detales siunčiame kelių transportu (surenkamieji kroviniai arba visa mašina), o mažas skubias detales – greitojo pristatymo kurjeriu; įprastas gabenimo laikas {to} yra {days} darbo dienos. Pristatome visoje šalyje, taip pat į pramonės centrus, tokius kaip {hubs}.',
 log_p3='Pristatymo sąlygos (pvz., EXW, FCA arba DAP jūsų gamykla) nustatomos pasiūlyme. Detalės nuvalomos, prireikus apsaugomos nuo korozijos ir supakuojamos transportavimui; prie kiekvienos siuntos pridedami lydimieji dokumentai, o pageidaujant – kontrolės protokolai.',
 faq_title='Klientų klausimai',
 faq=[('Ar pristatote CNC detales {to}?', 'Taip. Tekintas ir frezuotas detales, mazgus ir visas mašinas siunčiame {to} sunkvežimiu arba kurjeriu. Įprastas gabenimo laikas iš Satu Marės yra {days} darbo dienos, priklausomai nuo paskirties vietos ir transporto rūšies.'),
      ('Ko reikia pasiūlymui parengti?', 'Techninio brėžinio arba 3D modelio (PDF, STEP, IGES arba DXF), medžiagos, kiekio ir pageidaujamos pristatymo datos. Jei turite tik pavyzdį ar idėją, pradedame nuo reikalavimų ir suprojektuojame detalę už jus.'),
      ('Ar gaminate prototipus ir vienetines detales?', 'Taip. Gaminame prototipus, vienetines detales ir atsargines dalis, taip pat mažas ir vidutines serijas; kiekviena detalė apdirbama ir patikrinama mūsų dirbtuvėse.'),
      ('Kokia kalba galime bendrauti?', 'Mūsų komanda dirba anglų ir rumunų kalbomis. Pasiūlymai, brėžiniai ir lydimieji dokumentai rengiami anglų kalba; užklausą galite siųsti ir lietuviškai.')],
 faq_customs_q='Ar pristatant {to} mokamas muitas arba PVM?',
 con_tag='Kontaktai', con_title='Užklauskite pasiūlymo',
 con_p='Atsiųskite mums brėžinį ir reikalavimus – atsakysime su kaina ir pristatymo terminu.',
 l_phone='Telefonas', l_addr='Adresas', romania='Rumunija',
 f_name='Vardas', f_email='El. paštas', f_company='Įmonė (neprivaloma)', f_msg='Žinutė – aprašykite detalę ar projektą',
 f_send='Siųsti užklausą', f_sending='Siunčiama…', f_sent='✓ Išsiųsta – netrukus susisieksime.', f_error='✗ Klaida – bandykite dar kartą', f_missing='Įveskite vardą, el. paštą ir žinutę.',
 more_tag='Europa', more_title='Pristatome visoje Europoje', more_all='Visos šalys',
 bc_home='Pradžia', bc_eu='Europa', bc_page='{N}',
 nav_home='Pradžia', nav_services='Paslaugos', nav_contact='Kontaktai', skip='Į turinį',
 foot='CNC apdirbimas ir specialios mašinos, Satu Marė, Rumunija',
)
